DEFRA/water-abstraction-ui

src/controllers/licences.js
src/lib/permissions.js
src/lib/view.js
src/routes/VmL.js
src/views/water/dashboard.html
src/views/water/licence.html
src/views/water/licence_error.html
src/views/water/licences-add/add-licences.html
src/views/water/licences-add/security-code.html
src/views/water/licences-add/select-address.html
src/views/water/licences-add/select-licences-error.html
src/views/water/licences-add/select-licences.html
src/views/water/licences-add/verification-sent.html
src/views/water/licences_admin.html
src/views/water/licences_conditions.html
src/views/water/licences_contact.html
src/views/water/licences_map.html
src/views/water/licences_points.html
src/views/water/licences_purposes.html
src/views/water/licences_rename.html
src/views/water/licences_terms.html
src/views/water/manage_licences.html
src/views/water/manage_licences_add.html
src/views/water/manage_licences_add_access_form.html
src/views/water/manage_licences_added_access.html
src/views/water/manage_licences_remove_access_form.html
src/views/water/manage_licences_removed_access.html
src/views/water/update_password.html
src/views/water/updated_password.html

include dashboard link for admin users,
pass permissions to view layer
check for and assign admin permissions, initially adding 3 permission types : admin.[ defra | project | system ] (project and admin don't currently exist as roles)
modify all pages that contain "licences" link to show as "licences" or "your licences" depending on whether user is admin or not
only require access param at route and show start page on pre-prod (as this will be not provided by our service)
kitchen sink

add dashboard page

---

.gitignore
src/controllers/registration.js
src/controllers/serviceStatus.js
src/lib/VmL.js
src/lib/view.js
src/routes/VmL.js
src/views/index.js
src/views/water/accessibility.html
src/views/water/feedback.html
test/lib/VmL.js
test/lib/view.js

- Adds a new page for the accessibility statement
- Adds new route to show statement at `/accessibility`
- Adds the link to the new page in the footer support links.
- Changes the logic in the default view context to determine the
authenticated status using the SID to allow an authenticated user to be
identified even when browsing a page that does not require
authentication.
- Ran `npm run lint` which added some trailing semi colons.

feat/WATER-1069: Adds accessibilty page

---

src/lib/licence-transformer/index.js
src/modules/view-licences/helpers.js
test/modules/view-licences/helpers.js

bugfix/WATER-1119
Fixes a bug where the station does not report a valid level reading when
it is actually available.

Correctly identify level HOF types

---

src/modules/view-licences/helpers.js
test/modules/view-licences/helpers.js

Don't auto-select measure unless it matches a HoF condition in the licence.

Only auto-select flow/level if it matches a HoF.

---

.codeclimate.json
.labrc.js
index.js
package-lock.json
package.json
src/lib/connectors/water-service/notifications.js
src/lib/connectors/water.js
src/lib/hapi-error-plugin.js
src/modules/notifications/controller.js
src/modules/notifications/routes.js
test/modules/notifications/controller.js

Adds a route that is only accessible when `test_mode` is set to `1`.
This endpoint will return the most recently sent email notification for
a given email address.
- Adds a `.labrc.js` file to configure the global variables that are to be ignored by lab's leak checks.
- Adds code climate config to ignore migrations dir.

feat/WATER-1100: Last email by address route

---

src/views/water/notifications/data.html

Changes the containing column class to `column-full` from
`column-two-thirds` to allow the inputs to be slightly wider.

WATER-1070: Wider inputs

---

src/views/partials/licence-condition.html
src/views/water/view-licences/conditions.html

Changes the licence-condition partial to only include a line break if
the condition is not the last in an iterator.

WATER-1130 Removes extra spacing for conditions

---

src/lib/connectors/notify.js

Removes the `access=PB01` key value pair from the URL created in the
notification.
Joi does not allowed the `access` key because it is unexpected.

bugfix: Corrects URL when sharing with existing contact

---

src/lib/connectors/idm.js
src/lib/sign-in.js

This has been changed in the IDM to be an object, so this change
no longer treats the value as a string.

bug-fix: Fixes use of user_data from IDM

---

src/modules/notifications/contact-routes.js
src/modules/notifications/lib/task-data.js

WATER-1289
Changes the behaviour of Joi to collect all the validation errors rather
than existing on the first error.
This means that the forms will show all the errors at once to the user.
In this change, this effects the notification templates and the two
forms that collect the user's contact information prior to sending a
notification.

Bug-fix: Collect all validation errors

---

src/views/water/notifications/contact-details.html

WATER-1292
Adds the `novalidate` attribute to the form in the contact details page.

Bug-fix: Prevent browser validation on contact form

---

src/views/partials/error-summary-heading.html
src/views/water/contact-details/contact-information.html
src/views/water/notifications/contact-details.html
src/views/water/notifications/contact-name-job.html

WATER-1290
Adds the matching `id` values to the headings that are targeted by the
`aria-labelledby` attributed of the parent `div`.

Adds ids to headings in error alerts

---

.labrc.js
config.js
package.json
src/lib/connectors/idm.js

The IDM has changed to no longer have a on off switch for a user being
granted access to the admin application.
Now users are assigned to an application which will either be view my
licence or admin.
This has a dependency on [new IDM code](https://github.com/DEFRA/water-abstraction-tactical-idm/pull/48)

feature: Use IDM application over admin flag

---

_index.js
index.js
package-lock.json
src/lib/connectors/crm.js
src/lib/connectors/crm/entities.js
src/lib/connectors/crm/entity-roles.js
src/lib/connectors/idm.js
src/lib/constants.js
src/lib/hapi-plugins/acl.js
src/lib/hapi-plugins/permissions.js
src/lib/permissions.js
src/lib/sign-in.js
src/modules/abstraction-reform/routes.js
src/modules/auth/controller.js
src/modules/contact-details/routes.js
src/modules/manage-licences/controller.js
src/modules/notifications-reports/routes.js
src/modules/notifications/contact-routes.js
src/modules/notifications/routes.js
src/modules/view-licences/routes-admin.js
test/lib/permissions.js
test/modules/abstraction-reform/routes.js
test/modules/contact-details/routes.js
test/modules/notification-reports/routes.js
test/modules/notifications/contact-routes.js
test/modules/notifications/routes.js
test/modules/view-licences/routes-admin.js

WATER-1272
Makes use of new internal scopes for a user.
All admin routes now protected by 'scope' which is declared in the route
definition. A user must have the scope attached to the `credentials`
object.
- Updates hapi acl plugin to use sync getPermissions function
- Adds scopes to the `credentials` object via the session cookie.
- Adds a constants file to house the scope names.
- Updates the permissions module to derive permissions from the scopes
for internal users.
Related PRs:
[Admin UI](https://github.com/DEFRA/water-abstraction-admin-ui/pull/60)
[IDM](https://github.com/DEFRA/water-abstraction-tactical-idm/pull/52)

Feature: Use IDM roles for internal users

---

src/lib/permissions.js
src/lib/sign-in.js
src/modules/auth/controller.js
test/lib/permissions.js
test/lib/sign-in.js

Updates the permissions object so that an external user can have a
returns permission.
This may be a primary_user, or a user who has been allocated returns
permission by the primary user.

Feature: Handle user role with returns permission

---

src/lib/connectors/idm.js
src/modules/manage-licences/controller.js
src/modules/update-password/controller.js
src/modules/view-licences/base.js
src/modules/view-licences/routes-admin.js
src/modules/view-licences/routes.js
src/views/water/view-licences/licences.html
test/modules/view-licences/base.js

Use the `formError` if the email address is not valid.
Shortcuts the controller handler to prevent processing of bad input and
displays the feedback to the user.
Changes `getUser` to deal with numeric ids. No longer need to lowercase
the value either because this happens in the pre query filter in the
IDM.
Gets the user via the email address and application name to handle
multiple IDM entries for the same email address.
Adds form validation plugin validators which are required so the
formError is not truthy, covering page, sort and direction.

Fix: Shows email validation error

---

src/modules/manage-licences/controller.js

Throws the error rather than your the response toolkit. This is probably
a missed upgrade when going from Hapi 16 to 17.

Handles an error when granting licence access

---

src/lib/constants.js
src/modules/returns/controller.js
src/modules/returns/helpers.js
test/modules/returns/helpers.js

If the user is an authorised internal user, then do not add roles filter
to the request for returns licence numbers.
Adds constants for external user roles which attempt to use more domain
specific language

Fix: Allows authorised internal users to access returns

---

src/lib/hapi-plugins/error.js
src/modules/returns/admin-routes.js

When an internal user was requesting to look at a single return, the
route ACL that was copied from the external user was preventing access.
To fix, the internal user route is written to not include that part of
the external route config.

Fix: Internal user not seeing returns

---

src/lib/constants.js
src/lib/permissions.js
src/lib/view.js
src/modules/returns/admin-routes.js
src/modules/returns/external-routes.js
src/modules/view-licences/controller.js
test/lib/permissions.js
test/lib/view.js

Changes the permissions granted to a user for the `internal` and
`returns` roles.
Having `internal` allows a user to view returns.
Having `returns` allows a user to save returns.

Feat: Allow read returns for all internal users

---

package.json

Adds a new npm script that builds the local assets calling gulp.
This can then be called from the deploy script meaning that the project
can define it's own version of gulp locally rather than relying on the
globally installed version on the target machine.

Fix: Adds a new npm asset build script

---

src/modules/auth/routes.js

Allow the user to enter any length password and allow it through to be
validated by the idm rather than exiting early in the UI.

Fix: Don't validate password length on sign in route

---

src/lib/view.js
src/modules/auth/controller.js
src/views/partials/feedback-survey.html
test/lib/view.js
test/modules/auth/controller.js

Survey participants are now split into three groups:
- External
- Internal
- Anonymous
The appropriate survey id will be used if the user type can be
identified.
Also when the user signs out, a new query param will be used when making
the request to `/signed-out` so that the correct survey is shown.

Feat: Use user type specific survey identifiers

---

src/modules/returns/forms/meter-readings.js
test/modules/returns/forms/meter-readings.js

Fixes an issue reported where, when using large numbers, the meter
reading validation was not working and was allowing a user to enter a
reading that was lower than an earlier reading.

Fix: WATER-1450 validation logic

---

src/views/partials/feedback-survey.html

The smart survey was being added using a script tag. The iframe that is
rendered as a result contained a `onload` handler to scroll the user to
the bottom of the survey.
To fix, the iframe, without the onlonad hander is used in place of the
script tag.

Fix: Survey was scrolling down the page on signout

---

package.json
src/lib/forms/index.js
src/modules/returns/controllers/edit.js
src/modules/returns/forms/meter-readings.js
test/lib/sign-in.js
test/modules/returns/forms/meter-readings.js

WATER-1502
Fixes a bug with the validation of meter readings by changing the
validation schema to be created based on the values that are submitted.
The schema function now has to receive the data in order to create the
rules to enforce that a non null value is:
1) Greater than the meter start reading
2) Greater than the most recent non null reading

Fix: Corrects meter reading validation

---

src/views/water/returns/licence.html
test/modules/returns/helpers.js

WATER-1392
If the purpose alias is available then it is shown, otherwise show the
description of the tertiary purpose.

Feat: Adds purpose alias when showing returns

---

config.js
src/modules/returns/controllers/edit.js
src/modules/returns/forms/basis.js
src/modules/returns/forms/single-total.js
src/public/javascripts/application.js
src/views/water/returns/internal/confirm.html
src/views/water/returns/internal/form.html
src/views/water/returns/internal/nil-return.html
src/views/water/returns/licence.html
src/views/water/returns/meter-details.html
src/views/water/returns/meter-readings.html

WATER-1605
WATER-1606
Removes the JavaScript takeover on the back link which caused a history
back rather than a full refresh that pulled the new data from the
session.
To do this, an optional data attribute can be applied to elements marked
up with the `back-link` class to prevent this link being selected by
JQuery.
Update the basic and single total form objects to receive data rather
than pull from session themselves.
Also added to CSP header config to handle the images served by google.

Fix: Fixes returns back navigation

---

src/lib/unit-conversion.js
src/views/index.js
src/views/partials/return-quantities-table.html
test/lib/unit-conversion.js
test/views/index.js

WATER-1595
If a user entered no values then the total was calculated as `NaN`.
This was happening in a conversion function when `undefined` was passed.
So this fix returns `null` instead for `null` or `undefined` values.
Also tidies indentation of return-quantities-table to aid navigation.

Fix: Prevent NaN being shown for empty totals

---

src/lib/connectors/notify.js
test/lib/connectors/notify.js

WATER-1699
Fixes an issue with the licence holder name not appearing the letter
that contains a security code.
There are 6 available slots for name and address. Plus a separate slot
of postcode.
There are up to 8 address lines in a licence, so if all 8 are present,
the AddressLine4 data is omitted.

Fix: Includes lic holder name in security letter

---

package-lock.json
package.json
src/lib/sign-in.js
test/lib/sign-in.js

WATER-1730
When an agent becomes responsible for many licences, they in turn have
more items in the entity_roles array found when signing in.
This data is all serialized into the cookie, and once the user hits
three/four role pairs (user, user_returns) the amount of data being
added to the cookie for a given domain is too large. (Including GA as
well).
Therefore this quick fix maps the entity_roles picking out only the
necessary data. E.g. for 4 roles the length of the session data went
from ~4000 to ~1000 bytes.
There is a technical improvement story coming soon to only store a
session id in the cookie. But this approach is fast to implement and
will hopefully unlock users sooner.

Fix: Cookie too large for user with many roles

---

src/lib/connectors/crm.js
src/lib/connectors/crm/documents.js
src/modules/add-licences/controller.js
src/views/water/view-licences/licence.html

Fixes an issue where unverified licences were identified using a
verified flag which was just duplicated data.
This flag has been removed from the CRM now so this change updates the
UI layer accordingly.
WATER-1753

Fix: Check for verified licences using verification_id

---

gulpfile.js
package-lock.json
package.json
src/lib/view-engine/filters/form.js
src/views/nunjucks/abstraction-reform/add-data.njk
src/views/nunjucks/abstraction-reform/edit-data.njk

When a select element contains more than 200 items and the user permits
client side JS, the select is replaced with an accessible autocomplete
component.
Adds the govuk-body class to the form-group that contains the select to
allow the style to cascade into the list of options that replace the
select options.

Feat: Use accessible autocomplete for long selects

---

src/modules/abstraction-reform/controllers/wr22.js
src/modules/abstraction-reform/lib/helpers.js
src/modules/abstraction-reform/lib/schema.js
src/modules/abstraction-reform/lib/wr22-helpers.js
test/modules/abstraction-reform/forms/delete.js
test/modules/abstraction-reform/forms/select-schema.js
test/modules/abstraction-reform/lib/schema.js

WATER-1814
The json ref parser module was mutating the references of the schema for
WR22 so this change uses a function to return deep clones of the schema
objects so the references are resolved per licence condition.

Fix: Fixes an issue with mutated schema definitions

---

src/modules/abstraction-reform/lib/form-generator.js
src/modules/abstraction-reform/schema/types/water-bodies.json
src/public/javascripts/abstraction-reform.js
src/views/nunjucks/abstraction-reform/add-data.njk
src/views/nunjucks/abstraction-reform/edit-data.njk
test/modules/abstraction-reform/lib/form-generator.js

WATER-1815
Updates the usage of the accessible-autocomplete component to make
finding data without knowing its value upfront.
- Adds `defaultEmpty` to the JSON schema for water bodies
- Changes the form generator to use the `defaultEmpty` value to include
an empty value when enums are rendered as drop downs.
- Moves the client side JavaScript into an external file
(abstraction-reform.js) that can be used in the add and edit AR data
templates.

Feat: Improve configuration of accessible autocomplete

---

src/modules/abstraction-reform/schema/types/gauging-stations.json

WATER-1815
Configure the gauging stations JSON type to request that an empty value
is included in the rendered select element.

Feat: Include empty entry for gauging stations

---

index.js
src/lib/hapi-plugins/auth-credentials.js
src/lib/hapi-plugins/index.js
src/lib/hapi-plugins/licence-loader.js
src/lib/hapi-plugins/permissions.js
src/lib/sign-in.js
src/lib/view-engine/filters/form.js
src/lib/view-engine/handlebars.js
src/lib/view/main-nav.js
src/modules/add-licences/controller.js
src/modules/add-licences/routes.js
src/modules/auth/controller.js
src/modules/manage-licences/controller.js
src/modules/update-password/routes.js
src/modules/view-licences/controller.js
src/modules/view-licences/routes.js
test/lib/hapi-plugins/entity-roles.js
test/lib/hapi-plugins/licence-loader.js
test/lib/hapi-plugins/request-stub-plugin.js
test/lib/sign-in.js
test/lib/view/main-nav.js
test/modules/add-licences/controller.js
test/modules/registration/controller.js
test/modules/update-password/routes.js
test/modules/view-licences/controller.js
test/modules/view-licences/routes.js
test/test-helpers.js

WATER-1691
Extension of previous work for external users, this time dealing with
the internal users, whose permissions are based on scopes that used to
be included in the cookie.
This meant that the sign out - sign in cycle had to be completed to see
updated roles take effect.
Introduces a new plugin that operates in the onCredentials phase where
the user is loaded and the `request.auth.credentials` object is updated
with the user's scopes.
Also updates the handlebars pagination helper to make is handle an
undefined pagination object.
Adds licence loader plugin
Allows some licence data to be added to the request before the handler
is executed. This allows common licence data to be requested to save
duplicate code in the controller functions.
Makes use of the above plugin to update the …

Feat: Dynamically load internal user scopes

---

src/assets/sass/blocks/_badge.scss
src/modules/returns/controllers/view.js
src/modules/returns/lib/helpers.js
src/views/partials/return-due-badge.html
src/views/water/returns/index.html
src/views/water/returns/licence.html
src/views/water/returns/return.html
test/modules/returns/lib/helpers.js

WATER-1805
Internal user changes:
- Show void returns in returns list, with new void colour
- Show that a return is void in the return detail page.
External user changes:
- Void returns are hidden completely.
- Attempting to access a void return redirects user away (no code
required for this)

Feat: Handles returns with a void status

---

src/assets/sass/blocks/_badge.scss
src/modules/notifications-reports/controller.js
src/modules/notifications-reports/routes.js
src/views/partials/notify-status-badge.html
src/views/partials/return-due-badge.html

WATER-1858
Changes the CSS so that the `badge` class uses the inherited color for
text, which is then made white when a background is requested via a
modifier class.
After:
Before:

Fix: Fixes badge styles

---

src/assets/sass/application.scss
src/lib/connectors/crm/document-verification.js
src/lib/connectors/service-request.js
src/lib/connectors/water-service/licences.js
src/modules/view-licences/controller.js
src/views/water/view-licences/licence.html
test/lib/connectors/crm/document-verification.js
test/lib/connectors/water-service/licences.js
test/responses/water-service/documents/_documentId_/licence/users/index.js
test/responses/water-service/user/_userId_/status/index.js

WATER-1833
If the user is an admin, changes the licence detail page to show that a
licence is either unregistered, or who the licence is registered to.
- Adds the user name to the licence page if the licence has a primary
user.
- Updates the security code display to show the recipient address if a
verification code has been sent.
- Remove some unused CSS classes.

Feat: Adds registered user to licence detail page

---

src/assets/sass/v2/application.scss
src/assets/sass/v2/blocks/_text.scss
src/views/nunjucks/internal-search/macros/company-licences.njk
src/views/nunjucks/internal-search/macros/user-details.njk
src/views/nunjucks/macros/pluralise.njk

WATER-1833
- Use proper plurals for licence and licences in the user status page
- Allow email addresses to overflow onto the next line because they can
be too long for a single line in mobile view.

Fix: User status page visual bugs

---

package-lock.json
package.json
src/assets/sass/v2/application.scss
src/assets/sass/v2/blocks/_message-preview.scss
src/lib/connectors/water-service/communications.js
src/lib/view-engine/filters/index.js
src/lib/view-engine/filters/markdown.js
src/modules/view-licences/controller.js
src/modules/view-licences/routes-admin.js
src/modules/view-licences/routes.js
src/views/nunjucks/internal-search/macros/company-licences.njk
src/views/nunjucks/macros/pluralise.njk
src/views/nunjucks/view-licences/communication.njk
src/views/nunjucks/view-licences/tabs/communications.njk
test/lib/connectors/water-service/communications.js
test/lib/view-engine/filters/markdown.js
test/modules/view-licences/controller.js
test/responses/water-service/communications/_documentId_/index.js

WATER-1891
Adds a page that shows the message content that has been previously
sent.
- Updates marked module to latest version to use option to remove header
ids that are added to the output html.
- Replace pluralise macro with pluralize filter
- Adds the back link to the communication detail page
- Fixes an issue with the dates in the communications list.

Feat: Adds a communication viewer page

---

src/views/nunjucks/view-licences/licence.njk

WATER-1902
On the licence page, if the user is internal, and the primary user is
available, create a link to the user status page.

Fix: Changes an emailto link to a href

---

src/views/nunjucks/view-licences/tabs/communications.njk

WATER-1892
Updates the 'type' column text in the communications table to include
additional context for screen reader user agents.

Fix: Adds screen reader aware text in comms table

---

package-lock.json
src/modules/returns/controllers/edit.js
src/modules/returns/lib/return-path.js
test/modules/returns/lib/return-path.js

WATER-1954
Change logic to allow internal returns users to edit returns which are not void, are after summer 2018 and are past the end date. This is to include returns with a 'completed' status. Fix test to match logic change

Allow internal returns user to edit returns with 'completed' status

---

src/lib/hapi-plugins/auth-credentials.js
src/lib/hapi-plugins/company-selection.js
src/lib/hapi-plugins/index.js
src/lib/view.js
src/modules/manage-licences/controller.js
src/routes/public.js
src/views/nunjucks/auth/select-company.njk
src/views/nunjucks/layout.njk
src/views/partials/element-main-nav.html
test/lib/hapi-plugins/auth-credentials.js
test/lib/hapi-plugins/company-selection.js

WATER-1955
Fixes a bug where the user could end up on a page that is not the
company selector without having selected a company. This mean licence
lookups where not authorised so the user was redirected to the welcome
page.
This change updates the `auth-credentials` plugin to add more content to
the request under the `defra` property (to avoid collisions). This data
is then used in a `preResponse` handler to redirect the user either to
the `select-company` route if the user has companies, or the
`add-licences` route if they don't.
Also hides the company switcher if there is no company name selected
preventing it showing if the user has not selected a company but wishes
to update a password.

Fix: Prevent redirect of users to welcome page

---

src/lib/login-helpers.js
src/modules/auth/controller.js
src/modules/reset-password/controller.js
test/lib/login-helpers.js
test/modules/reset-password/controller.js

WATER-1967
FIxes a bug where the company switcher was shown to a user
after they had reset their password via the email route.
Moves the `login-helpers` module up to `/src/lib/` so it is accessible
to the `auth` and `reset-password` modules.

Fix: Don't show company switcher to single company users

---

src/modules/returns/controllers/edit.js
src/modules/returns/lib/return-path.js
test/modules/returns/lib/return-path.js

WATER-1971
Use returns editing logic for internal returns users to display 'Edit Return' button and when checking if return can be edited

Add check for returns editing for internal returns users

---

src/lib/connectors/water-service/returns-notifications.js
src/modules/returns-notifications/controller.js
src/modules/returns-notifications/forms/licence-numbers.js
src/views/water/returns-notifications/forms-confirm.html
test/lib/connectors/water-service/returns-notifications.js
test/modules/returns-notifications/controller.js

WATER-1950
Allow paper forms to be produced even if they have already been received
by updating the query filter to also included 'complete' returns.
Add licence ended reasons for notification preview to warn the user that
the licence is revoked/expired/lapsed.

Feat: Changes to paper form issuing

---

src/lib/connectors/api-client-factory.js
src/lib/connectors/water.js
src/modules/add-licences/controller.js
src/views/water/licences-add/verification-sent.html
test/lib/connectors/water.js
test/modules/add-licences/controller.js

WATER-1967
Fixes an issue where after a new user creates a security code, the
company was not set in the cookie meaning that the company switcher was
shown if the user navigated to the licences page.

Fix: Selects company when creating security code

---

src/modules/returns-notifications/controller.js
src/modules/returns-notifications/forms/licence-numbers.js
src/modules/returns-notifications/routes.js
src/views/water/returns-notifications/forms-confirm.html
src/views/water/returns-notifications/forms-success.html
src/views/water/returns-notifications/forms.html
test/modules/returns-notifications/controller.js

WATER-1950
Handles a bug where the presence of a date caused the licence to be
marked as expired/lapsed/revoked even if the date was in the future.

Fix: Sending paper returns to expired licences

---

src/modules/manage-licences/controller.js
test/modules/manage-licences/controller.js

WATER-1973
Fixes an issue where not toggling the user returns status for an agent
caused an error.

Fix: Prevent error when making no change to user returns

---

src/modules/returns/lib/return-helpers.js
src/views/nunjucks/returns/macros/confirm-page-inset-text.njk
test/modules/returns/lib/return-helpers.js

WATER-2014
If there are no meter details, or there is no estimate for the
abstraction, then don't show the inset text container.
Also fixes an issue with the meter details being override to a 1x
multiplier.

Fix: Prevent empty inset text container

---

src/views/nunjucks/returns/confirm.njk
src/views/nunjucks/returns/macros/return-header.njk

WATER-2019
Align return header with other elements on the page on 'Have you abstracted any water?' and Confirm pages

Fix alignment issues with returns header

---

src/modules/returns/lib/return-helpers.js
test/modules/returns/lib/return-helpers.js

WATER-2014
Updates the applyCleanUp function to ignore the updates to meters when
there is no meter information. This is for nil returns.

Fix: Prevent meter changes to external nil return

---

src/views/nunjucks/returns/submitted.njk

Aligns the link for 'View this return'

Fix: Spacing issue on return submitted page

---

src/views/partials/return-quantities-table.html

WATER-2017
Check if reading.type exists to display grey bar with inset text

Fix: Hide grey bar viewing completed return when there are no reading/meter details

---

src/modules/returns/controllers/internal.js
src/modules/returns/lib/flow-helpers/index.js
src/modules/returns/lib/flow-helpers/internal.js
test/modules/returns/lib/flow-helpers/index.js
test/modules/returns/lib/flow-helpers/internal.js

WATER-2038
Fixes a bug where the back link for the log return receipt was pointing
to the wrong location.
Also then fixes another issue where the back link on the internal
routing page contained the return id param, which caused a request
validation error. No goes directly to /licences as required.

Fix: Back link on log receipt for causing error

---

src/modules/returns/lib/return-helpers.js

WATER-2044
Add meters[0].meterDetailsProvided to applyMeterDetails page to ensure flags is used in both internal and external flows

Fix: Meter Details now being displayed on external confirm page

---

src/modules/returns/forms/meter-details.js
src/views/nunjucks/returns/confirm.njk
src/views/nunjucks/returns/macros/confirm-page-inset-text.njk
src/views/nunjucks/returns/macros/return-header.njk
src/views/nunjucks/returns/macros/return-quantities-table.njk

WATER-2042
- Shows the tariff type in the nunjucks confirm page
- Updates some of the text to be from the point of view or either an
external or internal user.

Fix: Show tariff details on confirm page

---

src/modules/returns/controllers/edit.js
src/modules/returns/controllers/internal.js
src/views/nunjucks/layout.njk
src/views/water/returns/internal/form.html
test/modules/returns/controllers/edit.js
test/modules/returns/controllers/internal.js

WATER-2054
Fixes issues with the post handlers for some of the returns flow pages
by adding the correct value for `back` when configuring the view context
ready to re-render the form.

Fix: Missing back buttons in forms with errors

---

src/assets/sass/v2/application.scss
src/assets/sass/v2/blocks/_badge.scss
src/assets/sass/v2/blocks/_warning.scss
src/lib/connectors/crm/documents.js
src/lib/connectors/water-service/licences.js
src/modules/returns/controllers/internal.js
src/modules/returns/controllers/view.js
src/modules/returns/lib/helpers.js
src/modules/view-licences/controller.js
src/modules/view-licences/routes-admin.js
src/views/nunjucks/internal-search/index.njk
src/views/nunjucks/returns/macros/return-header.njk
src/views/nunjucks/view-licences/expired-licence.njk
src/views/nunjucks/view-licences/macros/ended-licence-warning.njk
src/views/partials/return-header.html
src/views/water/returns/return.html
test/lib/connectors/crm/documents.js
test/lib/connectors/water-service/licences.js
test/modules/returns/lib/helpers.js
test/modules/view-licences/controller.js

WATER-1976
- Show expired licences in search results
- Add expired badge in expiry date column of search results
- Adds expired licences route to view details of expired licence
- Adds new badge and warning styles
- Updates view templates to handle links to expired licences
- Updates returns flow to direct user to expired, or current licence.

Feat: Show expired licences in search

---

src/lib/connectors/water-service/batch-notifications.js
src/lib/string-formatter.js
src/modules/notifications/lib/notifications-list.js
src/modules/returns-notifications/controller.js
src/modules/returns-notifications/forms/send-final-reminders.js
src/modules/returns-notifications/forms/send-reminders.js
src/modules/returns-notifications/routes.js
src/modules/routes.js
src/modules/waiting/controller.js
src/modules/waiting/routes.js
src/views/nunjucks/returns-notifications/reminders.njk
test/lib/connectors/water-service/batch-notifications.js
test/lib/string-formatter.js
test/modules/notifications/lib/notifications-list.js
test/modules/returns-notifications/controller.js
test/modules/returns-notifications/forms/send-final-reminders.js
test/modules/returns-notifications/forms/send-reminders.js

WATER-2087
Creates new page that starts the processing of the returns reminders.
- Adds new link to the reports and notifications page
- Create new page to start the process
- Adds placeholder route/controller for the waiting page
- Renames existing `send-reminders` form to `send-final-reminders`
Implementation of waiting page to be done in story 2089

WATER-2087

---

src/lib/forms/mappers.js
test/lib/forms/mappers.js

WATER-2121
When imported a value from a form using the number mapper. The string
value now has any commas removed before parsing to a float.
This fixes a potential 500 error seen at the moment if a user enters
meter readings using commas.

Fix: Remove commas in the number mapper

---

src/external/modules/abstraction-reform/lib/helpers.js

Abstraction reform helpers should reference local not shared licence
helpers

Fix: Fixes an incorrect require path

---

src/external/lib/hapi-plugins/index.js
src/external/modules/core/routes.js
src/internal/lib/hapi-plugins/index.js
src/internal/modules/core/routes.js
src/shared/lib/plugins/no-robots/index.js
src/shared/lib/plugins/static-assets/index.js
src/shared/lib/plugins/static-assets/routes.js
test/shared/lib/plugins/no-robots/index.js

WATER-1799
Creates a static assets plugin to provide static asset routes to the
internal and external applications.
Create a noRobots plugin that can be shared between the internal and
external applications.

Chore: Move static assets to shared plugin

---

src/external/views/nunjucks/form.njk
src/internal/views/nunjucks/form.njk

WATER-2142
Add div to make the title two-thirds width

Fix: FAO page title now two-thirds width

---

src/external/views/nunjucks/returns/macros/return-header.njk
src/internal/views/nunjucks/returns/macros/return-header.njk

WATER-2144
Fix returns header title to use h1 and h2 headings regardless of whether a licence has been given a name.

Fix: Returns header title

---

.codeclimate.json
src/external/lib/hapi-plugins/company-selection.js
src/external/lib/view/proposition-links.js
src/external/modules/account/controller.js
src/external/modules/account/forms/confirm-password.js
src/external/modules/account/forms/enter-new-email.js
src/external/modules/account/forms/verify-new-email.js
src/external/modules/account/routes.js
src/external/modules/add-licences/routes.js
src/external/modules/content/routes.js
src/external/modules/core/routes.js
src/external/modules/registration/routes.js
src/external/modules/routes.js
src/external/views/nunjucks/account/entry.njk
src/external/views/nunjucks/account/success.njk
src/external/views/nunjucks/account/try-again-later.njk
src/external/views/nunjucks/account/verify.njk
src/internal/modules/core/routes.js
src/shared/plugins/auth/routes.js
src/shared/view/nunjucks/filters/form.js
test/external/lib/hapi-plugins/company-selection.js
test/external/lib/view/proposition-links.js
test/external/modules/account/controller.js
test/external/modules/account/forms/confirm-password.js
test/external/modules/account/forms/enter-new-email.js
test/external/modules/account/forms/verify-new-email.js

WATER-2154
Update email UI and company selector update
- Includes new account-setting landing page
- Update email link commented out at this stage
- Includes confirm password page
- Adds page for adding new email address
- Adds page for email verification code
- Adds success page
- Adds the try again page for failed password attempts
Reworks the logic for the company selector which can now use the
`request.defra` object to help determine if a user should be redirected,
and also adds a settings item to allow a route to opt out of company
selector redirection. This came about because the user is logged in when
updating their account details so the existing mechanism of checking if
the route did not require authentication was no longer relevant.

Feat: Change email UI

---

package-lock.json
src/external/lib/licence-data-config.js
src/external/lib/view-licence-config.js
src/internal/lib/connectors/services/water/index.js
src/internal/lib/constants.js
src/internal/lib/licence-data-config.js
src/internal/lib/permissions.js
src/internal/lib/view-engine/filters/index.js
src/internal/lib/view-licence-config.js
src/internal/views/nunjucks/view-licences/licence.njk
src/internal/views/nunjucks/view-licences/tabs/charge.njk
src/shared/lib/connectors/services/water/ChargeVersionsService.js
src/shared/plugins/licence-data/index.js
src/shared/plugins/view-licence/controller.js
src/shared/plugins/view-licence/routes.js
src/shared/view/nunjucks/filters/charge-version-badge.js
test/internal/lib/permissions.js
test/internal/lib/view-licence-config.js
test/shared/lib/connectors/services/water/ChargeVersionsService.js
test/shared/view/nunjucks/filters/charge-version-badge.js

WATER-2267
- Adds the charge versions to the view-licence page.
- Adds a new tab if the user is authorised to view charge versions
- Handles the new 'charging' role in the permissions.

Feat: Charge versions in licence page

---

src/external/modules/add-licences/controller.js
src/external/modules/add-licences/routes.js
src/external/modules/returns/lib/helpers.js
src/internal/modules/abstraction-reform/lib/map-condition.js
src/internal/modules/returns/lib/helpers.js
src/shared/plugins/reset-password/controller.js
test/external/modules/add-licences/controller.js
test/external/modules/returns/lib/helpers.js
test/internal/modules/abstraction-reform/lib/map-condition.js
test/internal/modules/returns/lib/helpers.js
test/shared/modules/returns/forms/common.js
test/shared/plugins/reset-password/controller.js

WATER-2212
Reduces the noise in the errbit logs.
1) Downgrade a incorrect email as part of the reset password from error
to debug.
2) Downgrade an add licence error to a info log (LicenceSimilarityError,
LicenceMissingError)
3) Handles cleared session in the add licence flow
Deals with the user pressing back or refresh at the end of the add
licence flow which would attempt to extract data from a null session.
Instead now the user is redirected back to the start of the flow.
4) Adds more logging for map condition error
Current logging does not supply enough information to diagnose this so
added more logging to the `mapCondition` function to aid a fix in the
future.

Feat: Refine/reduce error logs

---

src/external/lib/hapi-plugins/index.js
src/external/lib/view.js
src/external/views/nunjucks/layout.njk
src/internal/lib/hapi-plugins/index.js
src/internal/lib/view.js
src/internal/views/nunjucks/layout.njk
src/shared/assets/sass/v2/application.scss
src/shared/assets/sass/v2/blocks/_cookie-message.scss
src/shared/plugins/cookie-message/index.js
test/external/lib/hapi-plugins/error.js
test/external/lib/view.js
test/internal/lib/hapi-plugins/error.js
test/internal/lib/view.js
test/shared/plugins/cookie-message/index.js

WATER-2233
Build cookie-message plugin to check for and add 'seen_cookie_message' cookie. Add seenCookieMessage to view context. Add cookie message to Nunjucks layouts.

Chore: Add cookie message to Nunjucks pages

---

server-external.js
server-internal.js
src/shared/plugins/returns/index.js
test/shared/plugins/returns/index.js

WATER-2320
Allows an internal users to submit returns against expired licences

Fix: Allow submission of expired licence returns

---

src/external/lib/hapi-plugins/index.js
src/shared/lib/connectors/services/water/AcceptanceTestsService.js
src/shared/plugins/acceptance-tests-proxy/controller.js

WATER-2230
Allow the payload of a request to be proxied through to the water
service to allow the caller to request specific data creation.

Chore: Proxy payload to acceptance tests routes

---

src/shared/lib/logger-factory.js

Removes a redundant call to logger.error that will not work due to the
position of the string in the arguments.

Fix: Remove call to logger.error

---

src/shared/view/nunjucks/macros/returns/return-quantities-table.njk

Fix spelling / sentence case of 'Cubic metres' heading in return quantities macro

Fix spelling / sentence case of 'Cubic metres' heading

---

package-lock.json
package.json
src/internal/lib/hapi-plugins/index.js
src/internal/lib/hapi-plugins/internal-user-id.js
test/internal/lib/hapi-plugins/internal-user-id.js

Adds a plugin that will update the request headers of outbound requests
handled by the `http` object from water-abstraction-helpers.

Feat: Pass internal user id on outbound requests

---

src/external/modules/core/controller.js
src/external/views/nunjucks/errors/404.njk
src/internal/views/nunjucks/errors/404.njk
src/shared/plugins/error/index.js
test/shared/plugins/error/index.js
test/shared/plugins/update-password/controller.js

WATER-2520
Fixes an issue in the shared error plugin where the 404 page title was
being set to the same text as if a server error had occurred.

Fix: Ensure 404 page title is correct

---

src/internal/modules/billing/controller.js
src/internal/modules/billing/pre-handlers.js
src/internal/views/nunjucks/billing/batch-list.njk
test/internal/modules/billing/controller.js
test/internal/modules/billing/pre-handlers.js

- Fixes an issue in the billing pre-handlers where the redirect did not take over the response when redirecting.
- Adjusts logic in billing list page to only show a link when batch status is `processing` or `ready` (these are the only 2 states that currently have working UI)

Billing list page issues

---

src/internal/modules/billing/controller.js
test/internal/modules/billing/controller.js

WATER-2554
For the new error handling in the batch process the event shape has
changed, so this change uses the new camel cased event id
Depends on https://github.com/DEFRA/water-abstraction-service/pull/815

Feat: Use new event shape in billing

---

src/internal/modules/billing/controller.js
src/internal/modules/billing/routes.js
src/internal/views/nunjucks/billing/batch-summary.njk
test/internal/modules/billing/controller.js

- Redirect user to batch summary when approved.
- Include query param if water service error so an error message can be displayed.

Handle errors approving batches

---

src/internal/modules/billing/controller.js
src/internal/modules/billing/routes.js
src/internal/views/nunjucks/billing/batch-summary.njk
src/internal/views/nunjucks/errors/error.njk
test/internal/modules/billing/controller.js

- Implements new content for internal error page
- On service error sending batch, displays error page instead of redirect 
- Bonus: hides confirm/send/actions on a batch not in `ready` status

Error handling for billing batch approve

---

src/external/modules/returns/controllers/upload.js
src/external/modules/returns/lib/upload-summary-helpers.js
src/external/views/nunjucks/returns/upload-summary.njk
src/shared/lib/connectors/services/water/ReturnsService.js
test/external/modules/returns/controllers/upload.js
test/external/modules/returns/lib/upload-summary-helpers.js
test/shared/lib/connectors/services/water/ReturnsService.js

WATER-2584
- Remove call to getUploadPreview without returnId.
- Update GET for bulk upload summary page to get view data from event metadata.

Feat: Persist user errors in bulk upload 

---

src/internal/views/nunjucks/billing/two-part-tariff-ready.njk
src/internal/views/nunjucks/billing/two-part-tariff-review.njk

bugfix/2PT-ready+review-UI
-- pluralize added to licence/s is/are text
--links to licences ready and licences review screen fixed

Fixes a link and pluralizes text for licence in 2PT screens

---

src/internal/modules/billing/forms/two-part-tariff-quantity-confirm.js
src/internal/modules/billing/forms/two-part-tariff-quantity.js
src/internal/views/nunjucks/billing/two-part-tariff-quantities.njk
test/internal/modules/billing/controllers/two-part-tariff.js
test/internal/modules/billing/forms/two-part-tariff-quantity-confirm.js
test/internal/modules/billing/forms/two-part-tariff-quantity.js

WATER-2772
When setting a transactions billable quantity use the maxAnnualQuantity
calculated in the water service when validating the user input.
Depends on https://github.com/DEFRA/water-abstraction-service/pull/1079

Feat: Use maxAnnualQuantity when setting billable quantity

---

src/internal/modules/charge-information/forms/start-date.js

bugfix/non-charge-flow
-- added Joi.required() to the start date form when custom date selected

Bigfix - Non charge flow - start date is required with custom start date selected

---

src/internal/lib/licence-data-config.js
test/internal/lib/licence-data-config.js

Resolves issue where licence page attempted to load charge version workflows from water service with insufficient scope

Charge version workflow scope bugfix

---

src/internal/modules/notifications/lib/permission.js
src/shared/plugins/returns/index.js

WATER-2430
Removes any extra args passed to Boom.unauthorized where they do not
adhere to the signature of the function.

Fix: Updates the use of Boom.unauthorized

---

.github/workflows/regression.yml
test/regression/external/helpers/loginAsUser.js
test/regression/external/reset-password.spec.js
test/regression/external/user-registration.spec.js
test/regression/internal/helpers/loginAsSuper.js
test/regression/internal/reset-password.spec.js
test/regression/shared/helpers/notifications.js
test/regression/shared/helpers/page.js
wdio.conf.js

This PR is a fork of the current regression packs, modified in such a way that they can now pass when run through a GitHub worker run. 
Last successful run can be found here: https://github.com/DEFRA/water-abstraction-ui/runs/1644886748?check_suite_focus=true
I recommend that `reg-pack/internal-password-reset-fork` is merged into `reg-pack/internal-password-reset`,
... And then `reg-pack/internal-password-reset` can be merged into `develop`.

Reg pack/internal password reset fork

---

src/internal/lib/connectors/services/water/InvoiceAccountService.js
src/internal/modules/billing-accounts/controllers/billing-accounts.js
src/internal/modules/billing-accounts/controllers/select-billing-account.js
src/internal/modules/billing-accounts/lib/mapper.js
src/internal/modules/billing-accounts/plugin.js
src/internal/modules/billing-accounts/pre-handlers.js
src/internal/modules/billing-accounts/routes/select-billing-account.js
src/internal/modules/charge-information/controllers/view-charge-information.js
src/internal/modules/charge-information/pre-handlers.js
src/internal/modules/charge-information/routes/view-charge-information.js
src/internal/views/nunjucks/billing-accounts/check-answers.njk
src/internal/views/nunjucks/billing-accounts/view.njk
src/internal/views/nunjucks/charge-information/view.njk
test/internal/lib/connectors/services/water/InvoiceAccountService.js
test/internal/modules/billing-accounts/controllers/billing-accounts.js
test/internal/modules/billing-accounts/controllers/select-billing-account.js
test/internal/modules/billing-accounts/plugin.js
test/internal/modules/billing-accounts/pre-handlers.js
test/internal/modules/charge-information/routes/view-charge-information.js

`WATER-2915`
Modifies billing account CRM plugin to:
* Include a flow for "update address"
* Post to the 2 new endpoints in the water service, 1 for 'create invoice account' and the other to 'create invoice account address'
Also:
* Links new flow in to billing account page
* Links charge information page to billing account page
* Bug fixes

Initial work on change billing account address

---

src/internal/modules/charge-information/forms/charge-element/quantities.js
test/internal/modules/charge-information/forms/charge-elements/quantities.js

Modifies the regex to allow for values starting with zero, as long as they're neither negative nor zero. E.g. 0.123 or 0.6
Relates to https://eaflood.atlassian.net/browse/WATER-3014

Alternative regex

---

src/shared/modules/returns/models/Lines.js
test/external/modules/returns/controllers/view.js
test/shared/modules/returns/models/Lines.js

WATER-3018
Fix issue where when editing already submitted returns, the return frequency/dates are not respected if there are errors in the lines data.

Force use of return lines frequency/dates when editing returns

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/lib/mappers.js
src/internal/views/nunjucks/billing/batch-invoice.njk
test/internal/modules/billing/controllers/bill-run.js

`WATER-3005`
Hides credit and debit blocks on invoice view except for WRLS supplementary batches

Show credit/debit block on invoice view only for WRLS supplementary 

---

src/internal/modules/billing/services/transactions-csv.js
test/internal/modules/billing/services/transactions-csv.js

Fixes an issue whereby deminimis was not showing correctly in the CSV following CM v2 switch.

Grab Deminimis flag from invoice level instead of transaction level

---

src/external/modules/notify/routes.js

WATER-3108
* Adds template_id and template_version to payload in route definition

Fix: Notify callback payload inputs

---

src/internal/views/nunjucks/billing/macros/invoices-table.njk

When a large report is generated it takes some time to completely build. Clicking the 'view' link before a report section is built will cause an error, so we hide the view link until the data is ready.

Hide the view link until the report is generated

---

src/internal/views/nunjucks/view-licences/tabs/charge.njk
src/shared/view/nunjucks/filters/charge-version-badge.js
src/shared/view/nunjucks/filters/date.js
test/shared/view/nunjucks/filters/date.js

Fixes issues with charge version workflows which are in "to_setup" status in the Charge Information tab
* Links work
* Badge displays correctly
* Dates default to hyphens since they are not yet set

Fix issues with charge version workflow in "to_setup" status

---

src/external/modules/returns/controllers/upload.js
src/external/modules/returns/lib/upload-helpers.js
test/external/modules/returns/controllers/upload.js
test/external/modules/returns/lib/upload-helpers.js

In bulk returns file upload page, uploading no file will cause the API to get through the full file process (creating an empty file, virus scanning, etc) and then return an invalid file message.
This change checks the user has actually uploaded a file first, and then returns the appropriate error if they haven't, without running through the whole file upload function.

WATER-2569: Throw an error if the user does not select a file to upload

---

src/internal/modules/billing/controllers/two-part-tariff.js
src/internal/modules/billing/lib/mappers.js
src/internal/views/nunjucks/billing/two-part-tariff-quantities-confirm.njk
src/internal/views/nunjucks/billing/two-part-tariff-quantities.njk
test/internal/modules/billing/controllers/two-part-tariff.js
test/internal/modules/billing/lib/mappers.js

Adds back the charge period to the TPT review screens, now that it is included in the billing volume API response

Include charge period in TPT review screens

---

src/internal/modules/charge-information/forms/start-date.js
src/internal/modules/view-licences/controller.js
src/internal/views/nunjucks/view-licences/tabs/charge.njk
test/internal/modules/charge-information/controllers/charge-information.js
test/internal/modules/charge-information/controllers/non-chargeable.js
test/internal/modules/charge-information/forms/start-date.js
test/internal/modules/view-licences/controller.js

bugfix/water-3198
-- remove today's date option for future dated licences

BUGFIX WATER 3198 - create charge versions for future dated licences

---

src/internal/modules/view-licences/controller.js

bugfix/water-3198
-- licences with end date null can create charge versions

Allow create charge versions where licences end date is null

---

src/internal/lib/mappers/returns.js
src/internal/modules/internal-search/lib/api-response-mapper.js
src/internal/modules/returns/lib/helpers.js
src/internal/modules/view-licences/controller.js
src/internal/modules/view-licences/lib/mappers.js
src/internal/views/nunjucks/internal-search/index.njk
src/internal/views/nunjucks/view-licences/tabs/returns.njk
src/shared/lib/returns/dates.js
test/internal/modules/contact-entry/controller.js
test/internal/modules/view-licences/controller.js
test/internal/modules/view-licences/lib/mappers.js

`WATER-3216`
* Fixes issue with "overdue" status not showing for returns
* Moves mapping of returns to shared location for internal site
* Other minor UI bugfixes

FIx issue with return status badge on internal licence page

---

cypress/integration/external/licence-alias-naming.spec.js

This PR is for the story - https://eaflood.atlassian.net/browse/WATER-3233 
This test covers below scenarios - 
- Creating the alias name 
- Changing the alias name to numbers 
- Changing the alias name to blank fields ( This is a negative scenario )

Positive and negative tests for external user licence alias name - WATER-3233

---

src/internal/modules/address-entry/pre-handlers.js
test/internal/modules/address-entry/pre-handlers.js

Jira ticket: https://eaflood.atlassian.net/browse/WATER-3269
EA-address-facade returns some addresses that have a `null` value for both `addressLine2` and `addressLine3` which causes validation within the water service to blow up.
After discussions with the wider team, it was decided as an immediate fix to remove invalid address options within the select address form (see jira ticket for discussion).

Bugfix/WATER-3269: Handle 'null' second line in address

---

src/internal/modules/charge-information/forms/charge-element/quantities.js
src/internal/modules/charge-information/lib/charge-elements/mappers.js
test/internal/modules/charge-information/forms/charge-elements/quantities.js

Ticket: https://eaflood.atlassian.net/browse/WATER-3288
This PR covers 2 things:
* fixes validation issues for optional billableAnnualQuantity
* fixes issue where optional billableAnnualQuantity was not saving to session state

Bugfix/WATER-3288 - Charge element quantities page failing when optional billable quantity is empty

---

cypress/integration/internal/invite-licence-holders-submit-returns.spec.js
cypress/integration/internal/remind-licence-holders-submit-returns.spec.js

https://eaflood.atlassian.net/browse/WATER-3227
This PR Consists 2 tests 
1) - User are invited to submit the returns 
2) - User are reminded about the returns 
Admin sends the invitations and reminders to the users to submit the returns. these are 2 separate tests.

returns invitations and reminders tests

---

package.json
src/internal/modules/customers/controllers.js
src/internal/modules/customers/forms/contact.js
src/internal/modules/customers/forms/index.js
src/internal/modules/customers/routes.js
src/internal/views/nunjucks/customers/contact.njk
test/internal/modules/customers/controllers.js
test/internal/modules/customers/forms/contact.js

See https://eaflood.atlassian.net/browse/WATER-3193
Please note this covers updating the contact name and forcing the entry of an email if it doesn't exist when setting the alerts to yes.
This requires both:
- https://github.com/DEFRA/water-abstraction-service/pull/1542
- https://github.com/DEFRA/water-abstraction-tactical-crm/pull/870
Please also note that the changes in the UI contain duplicates.  This was intentional as it would have been messy trying to reuse the code with one plugin, within another.

WATER-3193:Edit contact name including salutation

---

cypress/integration/internal/charge-version-flow.spec.js

This is an Automation for a recent production bug of Licence flagged for Supplementary bill run after adding a charge version.

Licence flagged for Supplementary bill is asserted

---

cypress/integration/internal/gauging-stations-and-water-abstraction-alerts.js
src/internal/modules/gauging-stations/forms/new-tag/threshold-and-unit.js
src/internal/modules/gauging-stations/lib/helpers.js
test/internal/modules/gauging-stations/lib/helpers.js

See: https://eaflood.atlassian.net/browse/WATER-3329
This is dependent upon: https://github.com/DEFRA/water-abstraction-service/pull/1583

WATER 3329: Addition of SLD as a unit type in the tagging flow

---

src/internal/modules/charge-information/forms/start-date.js
test/internal/modules/charge-information/controllers/charge-information.js
test/internal/modules/charge-information/controllers/non-chargeable.js

Removed restriction for start date to be up to last 5 years now can be anytime after the licence start date and before end date of licence.

WATER-3393 Removed restriction on start date

---

src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk
src/internal/views/nunjucks/charge-information/macros/charge-element-table.njk

The number filter has been removed to allow all 6 decimal places to be shown.
See: https://eaflood.atlassian.net/browse/WATER-3450

WATER-3450: Charge Screens inconsistent in Volume display

---

src/internal/modules/billing/forms/two-part-tariff-quantity.js
test/internal/modules/billing/controllers/two-part-tariff.js
test/internal/modules/billing/forms/two-part-tariff-quantity.js

See: https://eaflood.atlassian.net/browse/WATER-3451
- Prepopulate custom volume in the UI with the current volume when editing
- Add validation to prevent more than six decimals being entered in the UI for the custom volume 
Please note that this depends on: https://github.com/DEFRA/water-abstraction-service/pull/1603

WATER-3451: Edit flag not set correctly

---

src/internal/modules/charge-information/lib/reducer.js

See: https://eaflood.atlassian.net/browse/WATER-3496
Actual issue is the status of draft from the payload was not being saved when creating a charge element.

WATER-3496: Fix back button when adding a new charge version

---

src/internal/views/nunjucks/charge-information/macros/charge-element-table-alcs.njk
src/internal/views/nunjucks/charge-information/view.njk

Note: Only had to implement that the remove element button is shown when there is more than one element including charge categories.
See: https://eaflood.atlassian.net/browse/WATER-3476?focusedCommentId=378983

WATER-3476: Add the Remove element button on charge info review page

---

src/internal/views/nunjucks/billing/macros/two-part-tariff-review-quantities.njk

https://eaflood.atlassian.net/browse/WATER-3446
Currently the two-part tariff page displays `0Ml` for reported return if no return has been received. This could be misleading so we change it to display `No returns received` instead.

enhancement/water-3446 - Two part tariff `No returns received` message

---

src/internal/views/nunjucks/billing/macros/two-part-tariff-review-quantities.njk

https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3446
Following QA feedback, we amend the logic to ensure `No returns received` is correctly displayed when there is no return.

enhancement/water-3446 - Fix logic when displaying `No returns received`

---

src/internal/modules/charge-information/forms/charge-category/adjustments.js

https://eaflood.atlassian.net/browse/WATER-3634
The adjustment factor fields have been changed in the prototype to allow numbers with a large number of decimal places to be correctly displayed. We therefore change `controlClass` from `govuk-input--width-4` to `govuk-input--width-20` as specified in the prototype.

bugfix/water-3634 - resize charge creation factor fields

---

cypress/integration/internal/sroc-charge-version-flow.spec.js
src/internal/modules/charge-information/forms/charge-category/description.js
test/internal/modules/charge-information/forms/charge-categories/description.js

https://eaflood.atlassian.net/browse/WATER-3633
We update the UI validation to accept characters `&*()` in the charge reference description. The description in the card only refers to `&()`; the ACs however state that `&*()` should be accepted, and we use these as our "single source of truth". This also matches the validation rules required for import so we can be assured that we are being consistent across both manual and automated methods of entry.
Note that the import validation mentioned in AC3 has been added to the WIP import branch, so will be active once that branch is merged.

bugfix/water-3633 - Allow `&*()` in charge reference description

---

src/internal/views/nunjucks/billing/macros/invoices-table.njk

WATER 3644
Theres are multiple names associated with companies this work will introduce a new flow to determine what name to show (just an if else in the UI )
```
if invoice.faoContact 
elif invoice.billingContact.agentCompanyName 
elif invoice.billingContact.roleContact.licenceHolder
elif invoice.billingContact.roleContact.billing
else invoice.name
```

fix: billing contact account name

---

src/internal/modules/billing/services/transactions-csv.js
test/internal/modules/billing/services/transactions-csv.js
test/support/helpers/general.helper.js

https://eaflood.atlassian.net/browse/WATER-3586
We came across transactions-csv.js as part of working on altering the bill run download to handle SROC bill runs.
To say it angered and upset the current dev team is a bit of an understatement. You _could_ argue calling a function to pull a couple of fields from an object has value (though in our opinion you'd be wrong!)
But there is no reason for making an _utter_ mess of known conventions around `private` and `public` methods. It is a [common practice](https://stackoverflow.com/a/4484449/6117745) in JavaScript to prefix private module methods with an underscore. This singles intent to other developers; these methods are only used internally by the module, and those without it are for use elsewhere in the code.
So, after another day of …

Tidy up .../billing/services/transactions-csv.js

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/services/transactions-csv.js
test/internal/modules/billing/controllers/bill-run.js
test/internal/modules/billing/services/transactions-csv.js

https://eaflood.atlassian.net/browse/WATER-3586
We are updating the "download bill run" functionality to support sroc, which entails checking the bill run scheme and using a different set of output fields for alcs and sroc.

Export bill run CSV file for sroc

---

src/internal/modules/billing/services/transactions-csv.js
test/internal/modules/billing/services/transactions-csv.js

https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3586
Volume, Winter adjustment factor & Abatement factor were not appearing in the CSV. We fix this here:
* Volume is the transaction's volume -- this is the same as Quantity but we accept that this is acceptable for now.
* Winter adjustment factor was not being persisted in the db -- we [update the service](https://github.com/DEFRA/water-abstraction-service/pull/1722) to save this.
* Abatement factor is not provided by the Charging Module as previously assumed -- long story short, the Rules Service only returns factors that it calculates and since it uses the factor we provide, it therefore doesn't return a value. So rather than use the `calc` value (which is the one returned by the …

Fix export bill run csv for sroc

---

src/internal/modules/billing/services/transactions-csv.js
test/internal/modules/billing/services/transactions-csv.js

https://eaflood.atlassian.net/browse/WATER-3586
The Compensation Charge field is not correctly populated with `Y` for compensation charges. This is due to the expected `isCompensationCharge` flag not being present. We therefore replicate the logic of this flag in our CSV exporter.

Fix Compensation Charge field in CSV export

---

src/internal/views/nunjucks/gauging-stations/confirm-sending-alerts.njk

https://eaflood.atlassian.net/browse/WATER-3717
When creating a water abstraction alert, the alert will be sent by letter to the licence holder if no water abstraction alert contact has been added and opted in to receive email alerts.
We update the `confirm-sending-alerts` template to display the full set of address lines that we expect to receive.
Note that we also display `address_line_7` even though elsewhere we see a comment that there can only be 6 address lines plus postcode. We do this because the notifications report is set to display an `address_line_7` so even though we don't expect to receive it, we use it anyway just in case.

Postal address issue - water abstraction alerts

---

package.json

We add the `lint:fix` script to `package.json` which we omitted when we initially updated it from eslint to standard.

Add `lint:fix` script to `package.json`

---

src/internal/views/nunjucks/gauging-stations/confirm-sending-alerts.njk

https://eaflood.atlassian.net/browse/WATER-3717
When reviewing the UI changes for the postal address issue we realised that although we had added `notification.personalisation.postcode` to the template, this wouldn't actually be supplied by the service -- instead the postcode would come back as one of the numbered address lines. We therefore remove this from the template.

Postal address issue - Remove separate postcode field from template

---

src/internal/modules/charge-information/forms/charge-category/description.js
test/internal/modules/charge-information/forms/charge-categories/description.js

https://eaflood.atlassian.net/browse/WATER-3700
As part of the SRoC charge creation process, users need to enter a description for the charge reference. B&D want to be able to use ; (semi colon) and ' (apostrophe) in this description.
The list of allowed characters in WRLS is currently limited to letters (lower and upper case), hyphen (dash), numbers, forward slash, ampersand (&), asterisk , commas, brackets.
The following characters are not accepted by SOP “ ? ^ £ ≥ ≤ — (long dash).
We should allow ; and ' in WRLS, in addition to the currently accepted characters. We are amending to a 'not allowed' list instead, and only exclude those characters not accepted by SOP.

SRoC charge creation - additional characters required in charge reference description

---

src/internal/modules/charge-information/forms/charge-category/description.js
test/internal/modules/charge-information/forms/charge-category/description.js

https://eaflood.atlassian.net/browse/WATER-3700
The hint was not specified originally in the acceptance criteria and has since been added.
Also after some debate the error message has ben updated.

SROC charge creation - amend hint and error

---

src/internal/modules/charge-information/controllers/charge-category.js
src/internal/modules/charge-information/controllers/charge-information.js
src/internal/modules/charge-information/controllers/view-charge-information.js
src/internal/modules/charge-information/lib/charge-categories/constants.js
src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk
src/internal/views/nunjucks/charge-information/view.njk
test/internal/modules/charge-information/controllers/charge-category.js

https://eaflood.atlassian.net/browse/WATER-3702
When creating SRoC charge information, we want to skip the 'is abstraction for the supply of public water' question page if the licence holder is not a water undertaker. If we do skip this page then we ensure that `isSupplyPublicWater` is defaulted to `false`, by checking if it's been set by the time we get to the adjustments page at the end of the flow.

Skip public water question page if licence holder isn't water undertaker

---

src/internal/modules/billing/lib/mappers.js
src/internal/modules/billing/services/transactions-csv.js
src/internal/views/nunjucks/billing/macros/transactions-table-sroc.njk
src/shared/lib/number-formatter.js
src/shared/view/nunjucks/filters/charge.js
test/shared/lib/number-formatter.js
test/shared/view/nunjucks/filters/charge.js

https://eaflood.atlassian.net/browse/WATER-3733
When viewing the transactions as part of an annual bill run for SRoC, there is a section for each transaction showing charge period, charge reference etc.
The value of the charge reference, shown in brackets after the charge reference is displaying incorrectly. The conversion of the value from pence to pounds looks to be incorrect.

The charge ref is incorrect in the transaction detail

---

.git-blame-ignore-revs
src/external/modules/notify/controller.js
test/external/modules/notify/controller.js

https://eaflood.atlassian.net/browse/WATER-3746
When a Notify request is generated, Notify hits a callback endpoint to update the request status. The callback endpoint is on the production server which means that any non-prod requests (ie. a password reset on `pre`) will still result in the callback endpoint being hit. This should be fine, as the request id won't exist in prod and therefore nothing would be changed. Unfortunately, our callback endpoint was written without any error handling for such errors and therefore these requests from Notify would cause a small interruption while the server restarts after the unhandled error!
We therefore add simple error handling to ensure that such errors are caught without bringing down the production server for a few seconds.

Fix Notify callback exception

---

src/external/modules/notify/controller.js

https://eaflood.atlassian.net/browse/WATER-3746
After [fixing the issue of failed Notify callbacks bringing down prod](https://github.com/DEFRA/water-abstraction-ui/pull/2176), we update our code to log these failed callbacks.

Add logging to failed Notify callback

---

src/external/modules/notify/controller.js

https://eaflood.atlassian.net/browse/WATER-3746
We realised that our Notify callback logging wasn't appearing in the logs, as we only log errors and not info. We therefore bump the logging level up to warn (as changing the level to error would raise errbit errors for things like local password resets). We do this for both "callback resulted in error" and "callback failed due to wrong token".

Change logging level for Notify callback

---

src/external/modules/returns/routes/upload.js
src/internal/modules/charge-information-upload/routes.js

We've spotted that the charge version upload endpoint route specifies `5e+7` for `maxBytes`. Quick conversion means this is 50MB. However, the UI page says the max upload is 20MB.
We don't like inconsistency! So, this updates the info in the route config to match what we are stating on the upload page.

Make charge version max upload consistent

---

.git-blame-ignore-revs

https://github.com/DEFRA/water-abstraction-ui/pull/2174
We found [another change](https://github.com/DEFRA/water-abstraction-ui/pull/2017) in the commit history where masses of files were updated due to linting fixes. It's another thing that gets in the way when trying to see meaningful changes. So, we add it to our new `.git-blame-ignore-revs` file.

Hide big tech debt change with git blame ignore

---

src/internal/modules/billing/lib/mappers.js
test/internal/modules/billing/lib/mappers.js

https://eaflood.atlassian.net/browse/WATER-3753
When viewing the transactions as part of an annual bill run for SRoC, there is a section for each transaction showing charge period, charge reference etc.
If there is a TPT agreement, this should be shown in the Adjustments section. But it is not being displayed.

TPT adjustment not being displayed in transaction detail

---

.env.example
src/external/config.js
src/external/lib/view-engine/index.js
src/external/lib/view.js
src/internal/config.js
src/internal/lib/view-engine/index.js
src/internal/lib/view.js
src/shared/plugins/acceptance-tests-proxy/routes.js
src/shared/plugins/cookie-message/index.js
test/shared/plugins/cookie-message/index.js

https://github.com/DEFRA/water-abstraction-team/issues/43
We are currently using `NODE_ENV` incorrectly; we set it to be the name of the specific environment (eg. `local`, `qa` etc.) when it should be more like the _type_ of environment (e.g. is it a dev environment, a production environment, etc.)
This means that tools like pm2 aren't correctly picking up that we are running in a dev-like or prod-like environment and configuring accordingly.
We, therefore, change how we use `NODE_ENV` to be the type of environment, with a separate `ENVIRONMENT` env var to set the actual environment (eg. `tst`, `pre` etc.)

Correctly set NODE_ENV

---

src/external/views/nunjucks/returns/licence.njk
src/internal/views/nunjucks/returns/licence.njk

https://eaflood.atlassian.net/browse/WATER-3408
Here we have fixed a bug where the licence returns page was throwing an error when it got to the second page. This was caused by the next page and previous page link being passed a string rather then a varaible. We noticed the external returns page has the same bug (but unreported) so we have fixed this as well, as it was the same issue.

Fix licence returns pagination

---

src/external/modules/routes.js
src/internal/modules/routes.js
src/shared/modules/health/controller.js
src/shared/modules/health/routes.js
test/shared/modules/health/controller.test.js

https://github.com/DEFRA/water-abstraction-team/issues/54
This supports the new service-status page we're building in the [water-abstraction-system repo](https://github.com/DEFRA/water-abstraction-system).
We want to be able to show both the version and commit hash for each service on that page. The existing `/status` page does include the `package.json` version. But that endpoint is also used for the AWS load balancer health check so is heavily hit. We don't want to make it do more work getting the commit hash.
Instead, we add a new `/health/` path and a new `/info` endpoint to return both the version and commit hash.

Add new /health/info endpoint

---

.env.example
src/external/config.js
src/external/lib/view.js
src/external/views/nunjucks/add-licences/verification-sent.njk
src/internal/config.js
src/internal/lib/view.js
src/internal/views/nunjucks/add-licences/verification-sent.njk

https://eaflood.atlassian.net/browse/WATER-3816
When registering a new account, the end of the process triggers a verification code being sent to the customer's postal address. In our test environments, we display this code on the page so the user can continue without needing to receive the code by post. However it's been reported that this code recently appeared to a user in the production environment. We therefore fix this defect.
We do this by creating a new feature flag, defined in `.env` as `SHOW_VERIFICATION_CODE_FEATURE`, which displays the code when set to `true` but with an additional check so it is only displayed in non-prod environments. We then swap out the previous use of the `TEST_MODE` env var for our new feature flag.

Add feature flag to fix verification code appearing in production environment

---

src/shared/plugins/auth/index.js
test/shared/lib/plugins/auth/index.test.js
test/shared/plugins/auth/index.test.js

https://eaflood.atlassian.net/browse/WATER-3815
An external user reported seeing our SilverLine WAF error page. web-ops tracked this down to `Illegal HTTP status in response`. Basically, the service threw an unhandled error which caused it to return a http 500 response code. Responses like this are blocked because they typically leak information about the site.
We tracked down the issue being that the app was rejecting the request due to an invalid CSRF token (why, we'll never know!) That was then causing the error plugin to fire. In the event of a CRSF issue the error plugin will immediately log the user out using `request.logOut()`.
The problem is that function is attached to the Hapi request object in the auth plugin. It is also attached to the Hapi `onPreHandler` extension point, but …

Fix request.logout() is undefined error

---

server-external.js
server-internal.js
src/external/lib/connectors/services/water/NotificationsApiClient.js
src/external/modules/manage-licences/controller.js
src/internal/modules/abstraction-reform/lib/map-condition.js
src/internal/modules/billing-accounts/controllers/select-billing-account.js
src/internal/modules/service-status/controller.js
src/internal/modules/waiting/controller.js
src/shared/lib/connectors/services/water/NotificationsApiClient.js
src/shared/lib/logger-factory.js
test/external/lib/connectors/services/water/NotificationsApiClient.test.js
test/internal/modules/billing-accounts/controllers/select-billing-account.test.js
test/shared/lib/logger-factory.test.js

https://github.com/DEFRA/water-abstraction-team/issues/45
Here we are trying to make the error logs more usable. Currently when an error happens the logs are getting jammed up with thousands of lines making them difficult to read and unusable. This change stops that pollution making them more usable.

Stop passing err to logger.error

---

package.json

https://github.com/DEFRA/water-abstraction-team/issues/64
To help simplify things in our new Docker-based build environment and to take advantage of something we learned on [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) this change adds a post-install step.
If we're running `npm ci` you can be sure we also want to build our assets (we certainly should be!)
So, with this change that will happen automatically. We've left the old script command there for now whilst we update our various environments. But once that's done we'll drop `"install-assets": "gulp build",` from `package.json`.

Autobuild assets after npm ci

---

server-external.js

Spotted by our QA when some of the Cypress tests were no longer passing.
After lots of digging we tracked down the issue to a recent change where we [Removed hapi good - added hapi-pino](https://github.com/DEFRA/water-abstraction-ui/pull/2252).
The change caused a different argument order which we never spotted elsewhere and the existing tests didn't pick it up.
This change resolves the issue.

Fix server-common plugins

---

src/internal/modules/billing/controllers/create-bill-run.js
src/internal/modules/billing/lib/routing.js
src/internal/modules/billing/routes/create-bill-run.js
test/internal/modules/billing/controllers/create-bill-run.test.js
test/internal/modules/billing/lib/routing.test.js

https://eaflood.atlassian.net/browse/WATER-3828
Prior to this change, we were triggering the SROC supplementary bill run when the PRESROC reported back that it was finished. The mechanism for doing this is a spinner page that polls the bill run status. When it gets out of `processing`, we're go for SROC!
But we've quickly found relying on this existing feature is flaky at best and introduces a whole bunch of other issues. Also, it doesn't work with the view bill runs screen. There is nothing to stop a user from quitting the spinner page and coming back to view bill runs. They'll see PRESROC there, but not the SROC. The existing functionality treats creation and processing separately so we should do the same for SROC.
So, this change updates the UI to trigger the creation of the SROC bill …

Trigger SROC supplementary bill run in parallel

---

src/internal/modules/billing/lib/routing.js
src/shared/view/nunjucks/filters/batch-badge.js
test/shared/view/nunjucks/filters/batch-badge.test.js

https://eaflood.atlassian.net/browse/WATER-3874
When you run a bill run for a region and the service finds no applicable licences that need billing it directs you to an error page. The page tells you the reason is that the bill run is empty, so this fact is in the data somewhere!
What we and the users would ideally like to see is the bill run labelled as `EMPTY` in the view bill runs screen. As we'll have 2 distinct supplementary bill runs being generated each time it's important we can start distinguishing between those that have truly errored, and those where there was nothing to do.
<details>
<summary>Screenshot</summary>
</details>

Label empty bill runs as `EMPTY`

---

src/internal/modules/billing/lib/routing.js
src/internal/modules/billing/pre-handlers.js
src/internal/modules/billing/routes/bill-run.js
src/internal/views/nunjucks/billing/macros/batch-buttons.njk
src/shared/view/nunjucks/filters/batch-badge.js
test/internal/modules/billing/routes/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-3877
When a supplementary bill run is started, we'll be creating both a PRESROC and SROC one at the same time.
The PRESROC one will then begin `processing` (labelled as BUILDING in the UI) whilst the SROC one is `queued` waiting to be processed.
At the moment though, all we can do is initialise the SROC bill run with a status of `processing` as that is all that is available to us. In the UI this will give the impression both are building when they're not.
We've added a new `queued` status to [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service/pull/1965). This change updates the UI to add a new **QUEUED** badge and supports it.
<details>
<summary>Screenshot</summary>
</details>

Support new queued bill run status

---

src/internal/views/nunjucks/billing/batch-list.njk
test/internal/modules/billing/controllers/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-3664
With the introduction of SRoC, when running a supplementary bill run, it's possible that the bill run could pick up pre-SRoC and SRoC transactions. SOP has a constraint where they can’t deal with pre and post SRoC charges on the same bill run. Therefore supplementary billing will be split across two bill runs if there are a mixture of pre and post SRoC transactions.
To help B&D distinguish between the two charging schemes, we will add an annotation to pre-SRoC bill runs on the bill runs page - the annotation will be 'old charge scheme'.

Add charge scheme annotation to bill runs page

---

src/internal/views/nunjucks/billing/macros/batch-metadata.njk

https://eaflood.atlassian.net/browse/WATER-3869
B&D need to be able to identify if a bill run is pre-SRoC or SRoC. We do this by adding a `Charge scheme` field to the `batch-metadata.njk` template, which shows `Current` if the bill run scheme is `sroc` and `Old` if it's `alcs`.
Note that this template is a macro used by other templates and therefore will be displayed in other screens:
- `batch-creation-error.njk`
- `batch-invoice.njk`
- `batch-summary.njk`
- `batch-header.njk`
The calling controllers use `request.pre.batch` which is added by a prehandler calling `water-abstraction-service`; we therefore don't write any additional unit tests since we would be mocking the data returned by this anyway.

Add charge scheme to bill run view metadata

---

src/internal/views/nunjucks/billing/batch-processing.njk

https://eaflood.atlassian.net/browse/WATER-3870
When a bill run is processing the user sees the 'spinner page'. We now trigger the SROC bill run after the PRESROC has been completed. To the user though, this switch will be all but invisible (keen-eyed users will spot the batch ID change in the URL!)
The user needs some belief there has been progress, especially as running 2 bill runs will make the process longer. It will also help us to deal with issues, as they can identify which bill run is having a problem.
We therefore add a `Gathering transactions for old/current charge scheme` message to this page.
Note that as with previous UI changes, the `batch` object that's passed to the template is taken in its entirety from a call to `water-abstraction-service`; since we expect to get it …

Add charge scheme message to bill run spinner page

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/lib/routing.js
src/internal/modules/billing/pre-handlers.js
src/internal/modules/billing/routes/bill-run.js
src/internal/views/nunjucks/billing/batch-error.njk
test/internal/modules/billing/controllers/bill-run.test.js
test/internal/modules/billing/lib/routing.test.js
test/internal/modules/billing/routes/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-3882
When working on WATER-3833 it was tested what would happen if an error occurred.
If this happens in the legacy code the `billing_batch` has its `status` changed to error. In the UI it still gets listed with an **ERROR** label. In our new SROC supplementary bill run code though we weren't creating the record.
To ensure parity between the legacy and new code, we did some testing of what the legacy code actually does. What we found was _if_ it manages to throw and handle an error, it does set the `status` to 'error' and in some cases, it also sets an `error_code` against the bill run. But though the team thought there was an error page to display this information what actually happens is the service forwards the errored bill runs to …

Add new error page for errored bill runs

---

README.MD

Erm, all I can say is _doh_!
Note - There are loads more wrong in this repos' README but this is just so glaring!

Fix typo in name of repo in README

---

cypress.json

By default, for each test Cypress will record and then compress a video. These might be handy for sharing with those outside the team. But we never do! They can also help with debugging. But when we need to we just run the problem spec in the GUI.
So, it's another thing that is slowing the tests down and not adding any benefit.
This change disables videos by default.

Disable video in Cypress

---

cypress/plugins/index.js

Spotted in our Cypress acceptance tests that one of the URIs is defined differently from the others. No need for this. So, this is a quick change to make them consistent.
---
Also, added a `use strict` and denoted the first param as unused. We touched the file so did a little tidying whilst in there.

Make default env vars for Cypress consistent

---

cypress/support/commands.js

We hadn't spotted that when we made a change recently to [allow getting the last notification sent in our non-prod environments](https://github.com/DEFRA/water-abstraction-ui/pull/2267) that we broke the Cypress acceptance tests that depend on following these links, for example, password reset.
Simply put, the commands were premised on the endpoint being available in both the internal and external versions of the UI. Now it's only available in the internal version, we can tweak the commands and fix the issue.

Fix Cypress get email link commands

---

src/internal/modules/charge-information/controllers/charge-information.js
src/internal/modules/charge-information/controllers/view-charge-information.js
test/internal/modules/charge-information/controllers/view-charge-information.test.js

https://eaflood.atlassian.net/browse/WATER-3905
The business has raised an issue with the 'Check charge information' view. The scenario they outlined was
- Licence **AN/030/0008/006** was originally issued to _Cemex Materials Ltd_ with effect from 14/03/2022
- It was then transferred to _Breedon Trading Limited_ with effect from 27/06/2022
- Within the period 14/03/2022 - 26/06/2022 they would expect to see _Cemex Materials Ltd_ as the licence holder
- From 27/06/2022 we would expect to see _Breedon Trading Limited_ as the licence holder
This reminded someone that we'd had a similar issue previously. They found WATER-3348 which is linked to [Bugfix/water 3348](https://github.com/DEFRA/water-abstraction-ui/pull/1943). It seems that fixed the bug for the charge info view page …

Fix licence holder display bug in check charge info

---

src/internal/modules/charge-information/controllers/charge-information.js
src/internal/modules/charge-information/controllers/view-charge-information.js

https://eaflood.atlassian.net/browse/WATER-3905
We had a first stab at solving how the licence holder is displayed in the charge version review and check screens in [Fix licence holder display bug in check charge info](https://github.com/DEFRA/water-abstraction-ui/pull/2300).
That basically involved applying a fix implemented by the previous team to the charge version view screen to these screens. But our meticulous QA spotted that if you created a new charge version that starts on the day of an existing transfer you don't get the wrong holder, you get nothing!
This change fixes the issue for that edge case.

Fix licence holder display bug 4 date of transfer

---

src/internal/config.js
src/shared/plugins/hapi-pino.plugin.js

https://github.com/DEFRA/water-abstraction-team/issues/79
We have an ongoing problem where the log files for our apps very quickly become massive. In the space of a week, we can see a repo like [water-abstraction-returns](https://github.com/DEFRA/water-abstraction-returns) generate a log file almost 10Gb in size!
Fortunately, we have a solution in place for `production` that truncates them on a regular basis. But because we switch off our non-prod environments that process is often blocked there, meaning the logs get out of hand and use up all available disk space. It also means our local environments can be extremely noisy and if we don't switch them off, they too can run into the same issue.
So, for our background web services, we are changing the …

Make request logging configurable & change default

---

cypress/integration/external/notify-callback.spec.js
cypress/support/commands.js
cypress/support/notifications.js
package-lock.json
package.json

We'd already spotted that for some reason _another_ HTTP request package had been added to the repo just for use in Cypress. This was even more confusing because Cypress is itself a framework for sending HTTP requests!
Ideally, we'd like to run the current acceptance tests from the same repo we download as part of our Docker base local dev environment. You have to run the tests outside of the environment though because of the dependence on browsers being available. But because of the inclusion of [axios](https://github.com/axios/axios) as part of the dependencies any tests that rely on the custom commands that use **axios** fail.
So, this change removes **axios** and replaces what it was doing with native Cypress commands. It helps us remove a redundant package (that is also out of date) …

Remove axios from acceptance tests

---

src/internal/modules/address-entry/controller.js
src/internal/modules/address-entry/forms/select-address.js
src/internal/modules/address-entry/routes.js
src/shared/lib/form-handler.js
test/internal/modules/address-entry/controller.test.js

https://eaflood.atlassian.net/browse/WATER-3943
This was spotted when attempting to sign off the next release of the service and running through creating a new billing account with a new address during charge version creation. Having entered a postcode and searched for it you are presented with the drop-down of addresses found from which you must make a selection.
If you don't select anything and click continue, the validation message should be 'Select an address from the list'. Instead, the Ui is erroring and returning a `500` to the user.
This is not the result of a recent change, but one we made back in August 2022; [Remove catbox-redis](https://github.com/DEFRA/water-abstraction-service/pull/1794) from service So, the error has been present for some time. The reason given for adding …

Fix no address selected 500 error

---

src/internal/modules/view-licences/controller.js
src/internal/views/nunjucks/view-licences/licence.njk
test/internal/modules/view-licences/controller.test.js

https://eaflood.atlassian.net/browse/WATER-3948
We have an issue that the current `include_in_supplementary_billing` flag was added at a time there was only 1 charge scheme. A licence gets flagged irrespective of whether the change relates to PRESROC or SROC.
Where that has impacted us is when sending a billing batch. When it gets sent it clears the flag for _all_ licences included. But if we cancel one, for example, the PRESROC bill run, and send the SROC one we lose which licences still need to be processed on the PRESROC one.
[Our solution](https://github.com/DEFRA/water-abstraction-service/pull/2077) was to add a new `include_in_sroc_supplementary_billing` flag to the `licences` table and only set it to 'true' when an SROC charge version is approved. But this means a licence might be …

Highlight flagged for SROC supplementary billing

---

src/external/modules/returns/controllers/upload.js
src/external/modules/returns/lib/csv-templates.js
test/external/modules/returns/lib/csv-template.test.js

https://eaflood.atlassian.net/browse/WATER-3954
When trying to download the data for Bulk returns, you receive the Rejected URL error rather than the save file page.
This turns out to be because the zip file is generated as a stream in `objectMode` but hapi does not allow `objectMode` streams to be returned. We therefore need to wrap the zip file in a Readable stream to keep hapi happy.
Ideally, the zip file would not be generated as a stream in `objectMode` but we couldn't see anything in the Archiver package docs to indicate this is possible!
More info on hapi and `objectMode` streams can be found here: https://github.com/hapijs/hapi/issues/3733

Download of Bulk Returns Data Fails with Rejected URL

---

src/internal/modules/view-licences/controller.js
test/internal/modules/view-licences/controller.test.js

https://eaflood.atlassian.net/browse/WATER-3948
In [Highlight flagged for SROC supplementary billing](https://github.com/DEFRA/water-abstraction-ui/pull/2322) we made a change to the notice shown to users when a licence is flagged for supplementary billing. The first iteration of the wording was what us developers had put together based on the existing messages and changes elsewhere in the service.
Our UAT team have now had a chance to look at them and asked for some tweaks.
Pre-sroc (old charge scheme) needs to be
> This licence has been marked for the next supplementary bill run for the old charge scheme.
When a licence is flagged for both the old and new schemes
> This licence has been marked for the next supplementary bill runs for the current and old charge schemes.

Update include licence in supp. billing messages

---

src/internal/views/nunjucks/billing/batch-empty.njk
src/internal/views/nunjucks/billing/batch-error.njk
src/internal/views/nunjucks/billing/macros/batch-buttons.njk

We've been hitting the supplementary bill run process _hard_ over the last few months as we have tested and investigated the myriad scenarios we need to cover. During this we've noted we get many more `EMPTY` bill runs because of the need to kick off both PRESROC and SROC. It has also always puzzled us why you can't get rid of `ERRORED` bill runs.
So, this quick tweak adds the **Cancel** button to the empty and errored bill run pages to allow users to get rid of them from the listings. It might also help the performance of the page not to include these bill runs in the results.
<details>
<summary>Screenshot of bill runs page</summary>
</detail>

Enable cancel btn for empty & errored bill runs

---

src/internal/modules/billing/lib/mappers.js

https://eaflood.atlassian.net/browse/WATER-4001
Following the fix in https://github.com/DEFRA/water-abstraction-service/pull/2142, which fixed the issue where the incorrect value was being used for the Support Sources additional charges.
It has been found during testing that this value is incorrectly formatted from pence to pounds. As the corrected value is already in pounds and needs no conversion.
This PR will fix that issue by preventing the `numberFormatter.formatCurrency()` function from converting the value from pence to pounds by setting its `penceToPounds` value to `false` from its default of `true`.

Additional charges incorrect for supported sources

---

gulpfile.js
package-lock.json
package.json

https://github.com/DEFRA/water-abstraction-team/issues/78
After working on the issue [Swap out or remove Deprecated packages](https://github.com/DEFRA/water-abstraction-team/issues/22) for the [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui) in this [PR #2302](https://github.com/DEFRA/water-abstraction-ui/pull/2302) we found that in order to update/replace/remove some of the packages a significant amount of work was needed. These are therefore going to be done individually in separate PRs.
This PR removes the `del` package since we don't need to import a package just to delete a folder!

Remove package `del`

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/views/nunjucks/billing/batch-list.njk
test/internal/modules/billing/controllers/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-4030
The B&D frequently report issues with performance in the WRLS service. The same goes for errors when running bill runs.
This isn’t surprising to the new dev team based on how we now understand the service has been built and architected.
Since joining, we have advocated that the B&D should only run one bill at a time. We believe this will reduce the performance hit on the overall service and the likelihood of errors.
It seems that this message has not always been received or understood. Recent supplementary billing testing highlighted this when all the region leads were trying to test bill runs simultaneously.
This PR adds a notification banner to the 'Bill runs' page which is displayed if a bill run has a status of 'Building' or 'Queued'. …

Warn the user if a bill run is 'processing'

---

src/internal/modules/system-proxy/routes.js

We need to send POST requests to water-abstraction-system, for example, when calling `/data/tear-down`. So, we need to add a POST route to the system proxy routes to support this.

Add POST support to system proxy

---

src/internal/views/nunjucks/view-licences/licence.njk

https://eaflood.atlassian.net/browse/WATER-4033
It was found during some acceptance testing that a licence when viewed was displaying 'Licence number undefined'.
Initially, we thought it was a 'bad record' but when we investigated we found a subset of all licences will be affected by this. If the licence
- has a 'primary user' (an external user has added it to their account)
- is no longer active (has expired, lapsed or been revoked)
Then they will see 'undefined' in the view. This is because the view has this bit of logic
```
{% if not primaryUser %}
{{ title(licence.licenceNumber, 'Unregistered licence') }}
{% else %}
{{ title('Licence number ' + summary.licenceNumber, summary.documentName ) }}
{% endif %}
```
If there is a primary user it takes the licence number from the `summary` …

Fix licence number undefined in view

---

src/internal/modules/billing-accounts/controllers/billing-accounts.js
src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/services/transactions-csv.js
src/internal/views/nunjucks/billing/macros/invoices-table.njk

https://eaflood.atlassian.net/browse/WATER-3973
> TL;DR show the same name we send to the [Charging Module API's customer-changes endpoint](https://defra.github.io/sroc-charging-module-api-docs/#/customer/CreateCustomerChange).
-----
As part of creating a new billing account, you will select a 'customer (company)' and an address. Assume you selected the same 'company' as the previous charge version (the address doesn't matter).
You then get the option to create an 'FAO'. When you do you are creating a crm_v2.contacts record. This will automatically be linked to the company you selected to use for the new invoice account via a `crm_v2.company_contacts` record.
It will also create a new `crm_v2.invoice_account_addresses` record which links the address and new contact records to the …

Fix name used for billing contact

---

src/internal/views/nunjucks/notifications/preview.njk

https://eaflood.atlassian.net/browse/WATER-4101
This change prevents the 'Send Notification' button from being clicked twice when renewing reminder licences.

Prevent double button click for send notification for licence renewals

---

src/internal/modules/service-status/controller.js
test/internal/modules/service-status/controller.test.js

https://eaflood.atlassian.net/browse/WATER-4099
We are replacing the existing `/service-status` page with an updated version. But as all new code is being developed in [water-abstraction-system](https://github.com/water-abstraction-system) we need the UI to redirect the request to there.
This change just covers that. We'll look at what code we can delete when we are happy everything is working as expected.

Redirect /service-status to system app

---

src/internal/modules/service-status/controller.js
test/internal/modules/service-status/controller.test.js

https://eaflood.atlassian.net/browse/WATER-4099
In [Redirect /service-status to system app](https://github.com/DEFRA/water-abstraction-ui/pull/2426) we redirected the `/service-status` endpoint to `/health/info` in the [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) app.
But we were too clever and thought we needed the address for the system app. It works locally but in our AWS environments, the redirect would fail because you cannot access the system app directly.
So, instead, we need to redirect the request through the proxy implemented within the UI which passes requests onto our system app.

Fix service status redirect to system

---

src/internal/lib/connectors/services/system/BillRunsApiClient.js
src/internal/lib/connectors/services/system/BillingAccountsApiClient.js
src/internal/lib/connectors/services/system/index.js
src/internal/modules/billing-accounts/controllers/select-billing-account.js
test/internal/lib/connectors/services/system/BillRunsApiClient.test.js
test/internal/lib/connectors/services/system/BillingAccountsApiClient.test.js
test/internal/modules/billing-accounts/controllers/select-billing-account.test.js

https://eaflood.atlassian.net/browse/WATER-4092
We are working on migrating the change billing account address functionality from the legacy code to the [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), our new home for shiny, happy code! 🦄❤️
This change is the final part of the migration; updating the UI to send the request to the **water-abstraction-system** instead of the [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service).

Send change address requests to system in future

---

src/internal/modules/system-proxy/routes.js

https://eaflood.atlassian.net/browse/WATER-4085
https://eaflood.atlassian.net/browse/WATER-4155
In our new repo [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) we added a [new authentication plugin](https://github.com/DEFRA/water-abstraction-system/pull/351). We want this UI to be able to redirect users to new pages we create in **water-abstraction-system** and for that to be seamless and secure.
We could have managed authentication in our `src/internal/modules/system-proxy` module. But the idea is to move away from the legacy code base which means at some point **water-abstraction-system** needs to be doing authentication and authorisation.
So, we opted to perform the same checks there; admittedly we're performing authentication twice but it will give us …

Fix missing cookie in system proxy

---

src/shared/plugins/reset-password/forms/change-password.js

https://eaflood.atlassian.net/browse/WATER-4170
When changing your password, if you enter a new password without a symbol character you receive an error message.  This error message has a typo in it. This PR is to fix a typo.

Typo on Login Screen error message

---

.env.example
src/internal/config.js
src/internal/modules/billing-accounts/controllers/billing-accounts.js
src/internal/modules/billing/controllers/bill-run.js
src/internal/views/nunjucks/billing-accounts/macros/bills-table.njk
src/internal/views/nunjucks/billing-accounts/view-bills.njk
src/internal/views/nunjucks/billing-accounts/view.njk
src/internal/views/nunjucks/billing/batch-summary.njk
src/internal/views/nunjucks/billing/macros/invoices-table.njk
src/internal/views/nunjucks/view-licences/tabs/bills.njk

https://eaflood.atlassian.net/browse/WATER-4155
We are working on implementing a new version of the bill page. The current one tries to display all transaction details for all licences on a single page when the bill is selected.
In the larger annual bill runs this might equate to more than 150 licences and their transactions which means the page is failing to load.
All that work is being done in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) as part of our ongoing efforts to migrate away from the legacy code.
This means we need to update the UI to point to the system app and the endpoint we are building there when a user follows a view bill link.
We know there are 3 places we link to a bill; from the bill run summary, when looking at the bills for a selected …

Link to new bill page

---

src/internal/lib/connectors/services/system/BillRunsApiClient.js
src/internal/lib/connectors/services/system/BillingAccountsApiClient.js
src/internal/modules/billing-accounts/controllers/select-billing-account.js
src/internal/modules/billing/controllers/create-bill-run.js
test/internal/modules/billing-accounts/controllers/select-billing-account.test.js
test/internal/modules/billing/controllers/create-bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-4085
When we [enabled authentication by default](https://github.com/DEFRA/water-abstraction-system/pull/466) in **water-abstraction-system** we just had in mind requests proxied through or redirected from **water-abstraction-ui**.
We overlooked requests the UI was generating itself using `ServiceClient` from [water-abstraction-helpers](https://github.com/DEFRA/water-abstraction-helpers).
Doh! 🤦
So, we've inadvertently broken SROC supplementary billing and changing a billing account address because the requests we're sending to **water-abstraction-system** are being redirected to the `/signin` page.
The 'quick' fix would have been to remove auth off those routes but that would expose a vulnerability if we didn't then try to block them in …

Add cookie to http requests to system

---

src/internal/modules/billing/controllers/create-bill-run.js
test/internal/modules/billing/controllers/create-bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-4197
Following on from the work we did to create a trigger for the SROC two-part-tariff bill runs we have realised that the bill run can be triggered for billing periods outside of the SROC billing period.
This PR will fix that issue by preventing an SROC 2PT bill run from being triggered when the `financialYearEnding` is prior to 2023.

Prevent SROC 2PT being triggered when FYE < 2023

---

src/internal/modules/view-licences/controller.js
src/internal/views/nunjucks/billing/bills.njk

https://eaflood.atlassian.net/browse/WATER-4131
We have been working on replacing the existing views of a bill in the legacy code because they are slow and timeout when attempting to view large bills with many licences.
In [Link to new bill page](https://github.com/DEFRA/water-abstraction-ui/pull/2461) we thought we had updated all existing links that point to a bill to instead point to our new page.
But we missed one. After searching for a licence and having selected the 'Bills' tab there is a link at the bottom that takes you to a 'View all sent bills page'. If you click on a bill in there it takes you to the legacy view.
This change updates that link as well to point to the new bill view.

Link to new bill page from all sent bills page

---

src/internal/modules/billing/controllers/bill-run.js
test/internal/modules/billing/controllers/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-4131
The new bill pages we have been developing to replace the existing ones take a different approach to backlinks. Currently, in the service backlinks are intended to act like the browser back button. Clicking them should take you back to wherever you came from.
That's not the intent of backlinks in the design system though. When added to a page they _should_ take you back to the step or context before where you currently are. So, if you are on the bill page, you should go back to the bill run that the bill is linked to.
The browser back button is there for those who truly want to go back to wherever they came from.
Another reason for following this guidance is backlinks that just trigger `javascript:history.back()` are notorious for getting …

Make bill run summary page backlink fixed

---

src/internal/modules/billing/lib/routing.js
test/internal/modules/billing/controllers/bill-run.test.js

https://eaflood.atlassian.net/browse/WATER-4223
We have been working on implementing a new version of the bill page. The current one tries to display all transaction details for all licences on a single page when the bill is selected.
In the larger annual bill runs this might equate to more than 150 licences and their transactions which means the page is failing to load.
All that work has been done in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) as part of our ongoing efforts to migrate away from the legacy code. It is in the final throws of testing and will soon be released.
To get to the new pages you have to pass through the existing bill run summary page. What our work has highlighted is this page also leaves a lot to desire! Again, the larger the bill …

Redirect to new bill run page

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/views/nunjucks/billing/batch-sent-success.njk

https://eaflood.atlassian.net/browse/WATER-4223
We have been working on implementing a new version of the bill page. The current one tries to display all transaction details for all licences on a single page when the bill is selected.
In the larger annual bill runs this might equate to more than 150 licences and their transactions which means the page is failing to load.
All that work has been done in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) as part of our ongoing efforts to migrate away from the legacy code. It is in the final throws of testing and will soon be released.
Late in testing, we've spotted that the 'send a bill run' success page displays a 'Go to the bill run' link which is currently taking you to the old view.
So, this change applies a …

Redirect to new bill run page from batch sent page

---

src/internal/modules/returns-notifications/controllers/paper-forms.js

https://eaflood.atlassian.net/browse/WATER-4106
In [Generate unique job ID for paper return forms](https://github.com/DEFRA/water-abstraction-ui/pull/2458) we added a unique ID to the session created when generating paper form return notices. This was part of our efforts to avoid mis-clicks or double-clicks sending duplicate requests to generate the notices.
We didn't realise that some logic uses [Lodash](https://lodash.com/) to check the objects in the session for licences that do not have returns due.
```javascript
const licencesWithNoReturnsDue = data => Object.values(data).filter(row => !(has(row, 'document')))
```
This was fine when the session data looked like this
```javascript
{
'b79fdd34-d937-417c-86dd-f2f6ecf4b70f': 'AT/CURR/MONTHLY/01',
'ff571075-10bd-4583-b817-bb8dba7562fb': { …
```

Fix unique ID confused for licence in notice

---

server-external.js

https://eaflood.atlassian.net/browse/WATER-4352
https://github.com/DEFRA/water-abstraction-ui/pull/2507
When trying to access the external site, found there was an issue causing "This site can't be reached" being displayed.
Upon inspection, this was being caused by a missing import for proxying configuration within the external which was already present in the internal UI.
This change adds the configuration needed for the external site to work.

Fixing proxying to system from external UI

---

src/external/views/nunjucks/layout.njk
src/internal/views/nunjucks/layout.njk

GDS has released a new tudor crown for use for government that requires a flag to be set when calling it in the govukheader. this PR sets that flag to true.
https://eaflood.atlassian.net/browse/WATER-4353

Use new tudor crown

---

src/internal/modules/billing/lib/routing.js
test/internal/modules/billing/lib/routing.test.js

https://eaflood.atlassian.net/browse/WATER-4396
We have replaced the legacy version of the view empty bill run page with one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).
This updates the routing logic to return a link to the new view. If you look at the change you'll see this is the same route as when viewing a ready or sent bill run. In our new repo, we don't make separate routes based on status. Instead, it is one `GET /bill-runs/{id}` route to view a bill run and logic in the app will decide how the bill run is presented.

Link empty bill runs to view bill page

---

src/internal/modules/billing/lib/routing.js
test/internal/modules/billing/lib/routing.test.js

https://eaflood.atlassian.net/browse/WATER-4398
We have replaced the legacy version of the view errored bill run page with one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).
This updates the routing logic to return a link to the new view. If you look at the change you'll see this is the same route as when viewing a ready or sent bill run. In our new repo, we don't make separate routes based on status. Instead, it is one `GET /bill-runs/{id}` route to view a bill run and logic in the app will decide how the bill run is presented.

Link errored bill runs to view bill page

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/lib/routing.js
src/internal/views/nunjucks/billing/batch-list.njk
src/shared/view/nunjucks/filters/batch-badge.js

https://eaflood.atlassian.net/browse/WATER-4387
We need to add this to support our work to make cancelling bill runs visible to users.
Cancelling a bill run, especially a large one, can impact the service and take a considerable amount of time (30 minutes for the largest ones!) We want to let users know when a bill run is being cancelled so that they can make a more informed decision as to when it is best to try creating a new bill run.
We've amended [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service/pull/2450) to stop filtering bill runs with a status of `cancel` from the bill run results. The final step is to update this project to ensure they are displayed correctly in the table. This means they have a badge and no link to view the bill run.

Display cancelling bill runs in bill runs page

---

src/internal/views/nunjucks/billing/macros/batch-buttons.njk

https://eaflood.atlassian.net/browse/WATER-4387
In [Display cancelling bill runs in bill runs page](https://github.com/DEFRA/water-abstraction-ui/pull/2526) we made changes to help make cancelling bill runs more visible.
This was all built on the work we'd done to replace the legacy cancel bill run process with a new one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).
We overlooked that some pages in the legacy UI still need their cancel buttons re-pointed to the new endpoint. It was the PRESROC two-part tariff review page which caught our eye. But as we're updating a macro it'll mean any page that uses it will also benefit.

Update cancel btn in 2pt review to new process

---

src/external/views/nunjucks/view-licences/licences.njk
src/shared/assets/sass/_utils.scss

https://eaflood.atlassian.net/browse/WATER-4399
An issue has been raised where Licence Holders don't recognise the need to add licences to their account after a renewal and are missing their returns. There is already a feature in the service to add licences to an account so it has been agreed that a banner highlighting this is an appropriate intermediate step before full account management is tackled.
This adds the banner.
---
Out-of-the-box GOVUK enforces that banner content does get full with of the banner. It only gets approx 2 thirds (`max-width: 605px;` to be exact). Our designers decided that wrapping the content at 2 thirds looks 'odd' so this also involved some custom CSS to override the width of `govuk-notification-banner__content`.

Add reminder banner in external UI to add licences

---

src/internal/modules/billing/lib/routing.js
src/internal/views/nunjucks/billing/batch-processing.njk
test/internal/modules/billing/lib/routing.test.js

https://eaflood.atlassian.net/browse/WATER-4410
In WATER-4131 we resolved an issue with the legacy service not being able to display large bill runs without erroring. We did this by replacing the existing views with new ones. When we did this though we overlooked a feature; Remove licence from a bill.
We've since [put the button back in](https://github.com/DEFRA/water-abstraction-system/pull/824) to allow users to remove a licence from a bill. But because we are still dependent on the legacy service to do the removal we are also required to use its 'processing' page.
Initial testing showed that for this scenario it was redirecting back to the old view for a bill! So, this change fixes that issue.
Whilst making this change we've also dropped the cancel button from that processing (spinner) …

Redirect to new view after remove bill licence

---

src/internal/modules/billing/controllers/bill-run.js
src/internal/modules/billing/controllers/two-part-tariff.js
src/internal/modules/billing/lib/mappers.js
src/internal/modules/billing/lib/routing.js
src/internal/modules/billing/pre-handlers.js
test/internal/modules/billing/controllers/bill-run.test.js
test/internal/modules/billing/lib/routing.test.js
test/internal/modules/billing/pre-handlers.test.js

https://eaflood.atlassian.net/browse/WATER-4410
We realised recently that we'd inadvertently dropped the button that allows users to remove a bill licence from a bill. We've now put the button back in but this means the process has come under the beady eye of our QA team!
They've discovered that the spinner page often has a back link but clicking it can have varying results from 'page not found' to outright errors.
From looking at the legacy code we can see there was logic built in to make displaying the back link optional. If whatever code redirects to the spinner page doesn't include the appropriate option, the backlink will get displayed when it shouldn't.
~Or should it? A much simpler and cleaner solution that will work in all cases (the same spinner page is used for a host of …

Fix back link on billing spinner page

---

src/internal/config.js
src/internal/modules/charge-information/pre-handlers.js
src/internal/views/nunjucks/charge-information/workflow-tabs/to-set-up.njk
test/internal/modules/charge-information/pre-handlers.test.js

https://eaflood.atlassian.net/browse/WATER-4437
For context, we found out legacy background jobs scheduled in BullMQ only run intermittently. One we found hadn't run for the last 2 years so agreed to bin. Two we need to deal with at some point but intermittent is fine for now. The critical job, which is putting updated licences into workflow, we solved by migrating to [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system/pull/903).
As part of solving it we took the opportunity to add data to the workflow record to allow us to identify that the record was added because of an updated licence. We also spotted that our time-limited job was broken 😱 so [fixed that](https://github.com/DEFRA/water-abstraction-system/pull/908) and updated it to _also_ add some info to the …

Make manage workflow 'to setup' links intelligent

---

src/internal/views/nunjucks/view-licences/tabs/charge.njk

https://eaflood.atlassian.net/browse/WATER-4479
DEFRA/water-abstraction-acceptance-tests#88
When writing acceptance tests, due to the way [crypress](https://docs.cypress.io/guides/overview/why-cypress) works, some components of a page can be hard to locate.
For example, imagine a summary list which has nested values. This might be the address on the page provided by cypress:
```
':nth-child(2) > .govuk-summary-list.govuk-\!-margin-bottom-2 > :nth-child(1) > .govuk-summary-list__value'
```
To make it easier to locate the elements on the page we want to test, we add tags like so:
```
'<span data-test="meta-data-reason">' + reason + '</span>'
```
This PR is focused on adding tags to the views in the no-returns required journey.

Adding tags in view for acceptance tests

---

src/shared/modules/health/controller.js
test/shared/modules/health/controller.test.js

https://github.com/DEFRA/water-abstraction-team/issues/107
Currently, we have each app report details about itself on a `/health/info` endpoint. For each app this returns the current commit hash and the version recorded in `package.json`.
All this then gets shown in our main `/service-status` endpoint (or `/health/info` in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) if you want to go direct!)
Normally, when we cut a release we're ok to just take whatever is on `main` and tag that as the next version. We run `npm version [minor|patch]` and both the tagging and the updating of the version in `package.json` is done for us.
But in a recent release `main` in a couple of the repos contained changes we weren't yet ready to include. No problem, we just have to …

Stop using version in package.json

---

src/internal/modules/returns/controllers/internal.js
src/internal/modules/returns/controllers/view.js

https://eaflood.atlassian.net/browse/WATER-4558
> Part of the work to replace the legacy view licence page
It looks like when we did [Add feature flag for links to the water abstraction system](https://github.com/DEFRA/water-abstraction-ui/pull/2579) we missed some links that have been found in testing.
This changes updates where the code is redirecting or generating links to the legacy view licence page to instead link to the new one built in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).

Fix missed links to legacy view licence page

---

src/internal/views/nunjucks/customers/tabs/licences.njk

https://eaflood.atlassian.net/browse/WATER-4466
We have rebuilt the view licence pages in the system repo. As part of this work we introduced toggles in the old UI to direct user to the new view licence pages.
This link was missed by the previous work.

Fix customer licence view link toggle

---

src/internal/modules/charge-information/controllers/charge-information-workflow.js
src/internal/modules/charge-information/pre-handlers.js
src/internal/views/nunjucks/charge-information/workflow-tabs/review.njk
src/internal/views/nunjucks/charge-information/workflow.njk
src/internal/views/nunjucks/notifications/manage-tab.njk
test/internal/modules/charge-information/controllers/charge-information-workflow.test.js

https://eaflood.atlassian.net/browse/WATER-4570
With WRLS taking over return information when a licence is added or changed and a record is added to workflow, the workflow record needs to direct users to check both return and charge information, not just charge information. It also needs to stop referring to ‘charge information’ only, for example, in the link on the manage page and on the page itself.
This PR is focused on amending the /manage page and it's subsections for the new licence set up view.

Update /workflow page to remove 'charge' elements

---

src/external/modules/account/controller.js
src/external/views/nunjucks/account/verify.njk

https://eaflood.atlassian.net/browse/WATER-4632
We received a report that the external app's change email journey was broken. We quickly confirmed this.
Nothing related to the fix needed to be made to this project. But such a critical feature shouldn't have been allowed to sit broken for so long.
To ensure this (until we can replace the legacy version), we've [added a test](https://github.com/DEFRA/water-abstraction-acceptance-tests/pull/131) to our automated test project. The problem is that the journey relies on sending the user an email code, which they then need to enter.
This change copies a solution that has been used before, where the code is displayed on the screen if the feature toggle `SHOW_VERIFICATION_CODE_FEATURE` has been enabled.
Our acceptance tests can then read this and …

Display security code in ext. change email page

---

src/internal/modules/internal-search/controller.js
src/internal/views/nunjucks/internal-search/macros/company-licences.njk
src/internal/views/nunjucks/internal-search/macros/user-companies.njk
src/internal/views/nunjucks/internal-search/user-status.njk

https://eaflood.atlassian.net/browse/WATER-4558
> Part of the work to replace the legacy view licence page
Spotted whilst [fixing an issue in the water-abstraction-system](https://github.com/DEFRA/water-abstraction-system/pull/1291) version of the view licence page. The links in the `/user/{id}/status` page still point to the old view.
After taking a look, we realised
- feature flags were never actually being passed to the view
- the flags were not being passed through the many (_many_ 😩) layers of macros to where it was being used
- the link we would have generated would have been broken
This change fixes all those issues and gets the link working.

Fix links to system view licence in /user/*/status

---

src/internal/lib/connectors/services/system/LicencesApiClient.js
src/internal/lib/connectors/services/system/index.js
src/internal/modules/returns/controllers/edit.js
src/internal/modules/view-licences/controller.js
src/internal/modules/view-licences/forms/mark-for-supplementary-billing.js
test/internal/lib/connectors/services/system/LicencesApiClient.js
test/internal/modules/view-licences/controller.test.js
test/internal/modules/view-licences/forms/mark-for-supplementary-billing.test.js

https://eaflood.atlassian.net/browse/WATER-4199
When a return is submitted or edited the user is given the chance to flag the licence for the next supplementary bill run. As part of our work to create a two-part tariff supplementary bill run, we also need the same functionality to flag licences for our new bill run type. This PR is setting up the UI to call our endpoint in system that determines which years on the licence need to be flagged.

Add system supplementary flag for returns

---

src/internal/modules/view-licences/controller.js
test/internal/modules/view-licences/controller.test.js

https://eaflood.atlassian.net/browse/WATER-4199
https://eaflood.atlassian.net/browse/WATER-4676
During testing for the first ticket, it was discovered that editing a return on a licence and then flagging that licence for supplementary billing, was always flagging the licence for pre-sroc supplementary billing even when the years were for sroc. 
The system now handles flagging a licence for two-part tariff supplementary, so this change is allowing system to handle all the flagging for editing a return. 
The `postMarkLicenceForSupplementaryBilling` function is being used during two flagging routes. 
The first is when a return is edited. As we now handle that in system the call to the UI just passes the information for system to work out if the licence for the edited return needs to be …

Amend mark for supplementary billing

---

src/shared/view/nunjucks/macros/returns/return-header.njk

https://eaflood.atlassian.net/browse/WATER-4703
If a return log was created from a return requirement with no site description, when a user views the return log in the UI they see `null`.
We've agreed that we should display nothing when this is the case. This change updates the legacy view to handle this scenario.

Stop display null for site description in view rtn

---

package-lock.json
src/internal/config.js
src/internal/views/nunjucks/internal-search/index.njk
src/shared/view/default-context.js

https://eaflood.atlassian.net/browse/WATER-4679
While adding the feature flag for the monitoring stations for the license summary page, we realised that the monitoring station can also be reached via the internal search tool. This could mean users are at one point in the journey being shown the new migration monitoring station page, and at another point are shown the legacy monitoring station view.
This PR adds the feature flag functionality to the UI internal search tool to send users to the new monitoring station view.

Add monitoring stations feature flag for search

---

src/internal/lib/connectors/services/system/WorkflowApiClient.js
src/internal/lib/connectors/services/system/index.js
src/internal/modules/charge-information/controllers/charge-information-workflow.js
test/internal/lib/connectors/services/system/WorkflowApiClient.test.js
test/internal/modules/charge-information/controllers/charge-information-workflow.test.js

https://eaflood.atlassian.net/browse/WATER-4137
As part of the work to flag licences for the new two-part tariff supplementary billing, we need to be able to flag licences that are removed from the workflow. If a licence is in workflow it does not get picked up for annual billing. This means if the licence is removed without any new charge information added, then we risk the licence not being billed for the year. This change adds a call to our supplementary endpoint in the system repo, which will flag the licence for two-part tariff billing if it meets the criteria.

Flag licences removed from workflow for supp billing

---

src/internal/modules/gauging-stations/controller.js
src/internal/views/nunjucks/gauging-stations/new-tag-complete.njk

https://eaflood.atlassian.net/browse/WATER-4736
In our last release, we shipped a new version of the view monitoring station page, replacing the legacy one. However, we quickly received feedback that the dates we display for tagged licences don't look right.
We've [fixed those issues](https://github.com/DEFRA/water-abstraction-system/pull/1470), but our QA team have spotted that several of the journeys started on that page still return you to the legacy page.
This change updates those links to the view monitoring station page we missed the first time to redirect to our new page based on the feature flag.

Update missed links to new view monitoring station

---

src/internal/modules/gauging-stations/controller.js
src/internal/views/nunjucks/gauging-stations/new-tag-complete.njk

https://eaflood.atlassian.net/browse/WATER-4736
In [Update missed links to new view monitoring station](https://github.com/DEFRA/water-abstraction-ui/pull/2638), we updated some links to point to our new view monitoring station page that had been missed when first doing this work.
However, we broke a link that must point to a legacy URL.
This change fixes the link we broke.

Fix invalid link on tagging licence complete page

---

src/shared/modules/system-proxy/routes.js

We use proxying to send requests from the legacy system to the `water abstraction system` for our new services. We need to also add the routes for proxying images, similar to the proxying of other assets like scss.
This PR adds proxying for images to the system proxy routes.

Add proxies for image asset requests to WRLS

---

src/shared/lib/services/hapi-pino-serializers.service.js
src/shared/plugins/hapi-pino.plugin.js
test/shared/lib/services/hapi-pino-serializers.service.test.js

We've completed a [number of changes to our logging](https://github.com/DEFRA/water-abstraction-team/issues?q=is%3Aissue%20state%3Aclosed%20log) in the time we have been on the project.
Generally, we 'go to the logs' when an issue has been reported in `production`, and we need to figure out what has happened.
Therefore, we constantly balance, ensuring we have all the necessary information while excluding noise.
We recently [made a change to water-abstraction-system](https://github.com/DEFRA/water-abstraction-system/pull/1655) to reduce the noise in our logs via custom serializers (check it out for more details).
This change makes the same change to the logging in this app.

Add custom serializers to improve app logging

---

package-lock.json
package.json
server-common.js
src/external/config.js
src/internal/config.js

https://github.com/DEFRA/water-abstraction-team/issues/111
Along with most other Defra services, we add this as a project standard. But we've been (rightly) challenged on what value this adds.
On [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), we concluded it was very little and was against our ethos of 'minimal and simple', so [we removed it](https://github.com/DEFRA/water-abstraction-system/pull/1080).
This change removes it from this app.
> Note: we don't remove the `description:` property from the routes. Eventually, this repo will become redundant, so it was deemed unnecessary.

Remove blipp plugin

---

package-lock.json
src/internal/modules/manage/lib/manage-nav.js
test/internal/modules/manage/lib/manage-nav.test.js

https://eaflood.atlassian.net/browse/WATER-4899
As part of the work to implement notifications in the system repo we have multiple journeys for notifications.
This change updates the paths for invitations and ad-hoc returns.
The paths point to the same endpoint with a different query string highlighting which notification type has been chosen.

Update notifications setup redirect path

---

src/internal/modules/manage/lib/manage-nav.js

https://eaflood.atlassian.net/browse/WATER-4900
This change updates the notifications reminders link to redirect to the system notification setup journey.
The journey key is set to 'reminders' to match the expected query string.

Add notifications reminders link

---

src/external/modules/returns/lib/helpers.js
test/external/modules/returns/lib/helpers.test.js

https://eaflood.atlassian.net/browse/WATER-4953
Before this change, the bulk upload link in the external UI would only display if there were due returns, flagged for bulk upload, that matched the current return cycle.
Quarterly has changed the submission model from once to four times a year. Therefore, the existing functionality that switched between the summer and winter cycles based on the time of year will no longer work because the submission cycles now overlap.
We must update the logic to determine whether to display the link or ignore the current cycle. In short
- Are there any due returns?
- Do they have an end date less than or equal to the current date? (You can't submit a return that hasn't ended.)
- Do any of them have the `isUpload` flag set to true?
We must display the link …

Always display bulk upload link on external site

---

src/external/modules/returns/controllers/upload.js
src/external/modules/returns/lib/csv-templates.js
src/shared/lib/connectors/services/water/CompaniesService.js
test/external/modules/returns/controllers/upload.test.js
test/external/modules/returns/lib/csv-template.test.js
test/internal/modules/returns/controllers/edit.test.js
test/shared/lib/connectors/services/water/CompaniesService.test.js

https://eaflood.atlassian.net/browse/WATER-4796
We are updating the service to allow customers to upload returns quarterly (four times a year instead of just once).
The current logic tied displaying the link and generating the CSVs to the cycle you were currently in. To enable quarterly, we have to break that tie-in and move to a more flexible "I have a due return; give me the CSV!"
We've already made a change to allow the link to always be displayed (if you have bulk uploads enabled and have due returns) in [Always display bulk upload link on external site](https://github.com/DEFRA/water-abstraction-ui/pull/2677).
This change is about the changes needed to the CSV template generation.
They are
- Split out the CSV files further based on the 'due date' of the returns we're processing
- …

Update upload CSV generation to support quarterly

---

src/internal/modules/billing-accounts/controllers/billing-accounts.js
src/internal/modules/billing-accounts/routes/billing-accounts.js
test/internal/modules/billing-accounts/controllers/billing-accounts.test.js

https://eaflood.atlassian.net/browse/WATER-4988
While working on the view billing account page in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), we noticed an issue with the change address button. Although we used the same endpoint as the legacy page, it brought up an error whenever loading in from the new system. After some digging, this was concluded to be because of some complex manipulation of the request by the legacy system.
To get around this, we introduced a new dedicated endpoint for the change address flow when accessed from the view billing account page. This avoids the quirks of the legacy implementation and allows the new system to handle the logic in a cleaner and more predictable way.
This PR will add a new endpoint for the change address …

Add new endpoint for change address button to UI

---

src/internal/config.js
src/internal/modules/internal-search/lib/redirect-to-billing-account.js
test/internal/modules/internal-search/controller.test.js
test/internal/modules/internal-search/lib/redirect-to-billing-account.test.js

https://eaflood.atlassian.net/browse/WATER-4988
After completing the view billing account page in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), it was noticed during testing that searching for a billing account would redirect to the legacy billing account page. When a user searches for a billing account, it should redirect to the new billing account page created.
This PR will amend searching for a billing account to redirect to the new billing account page.

Access view billing account page via search

---

src/internal/modules/billing-accounts/controllers/select-billing-account.js
test/internal/modules/billing-accounts/controllers/select-billing-account.test.js

https://eaflood.atlassian.net/browse/WATER-4988
While working on the view billing accounts page, it was noticed that after a user goes through the change address journey, it would redirect to the legacy billing accounts page.
This PR fixes the redirect to sent users back to the new billing account page.

Update change address redirect to new billing account page

---

src/shared/lib/connectors/services/water/CompaniesService.js

https://eaflood.atlassian.net/browse/WATER-4796
We are updating the service to allow customers to upload returns quarterly (four times a year instead of just once).
In [Update upload CSV generation to support quarterly](https://github.com/DEFRA/water-abstraction-ui/pull/2679), we 'broke' the logic that tied the templates generated to only those in the current cycle. Instead, it is a more flexible "I have a due return; give me the CSV!"
However, during testing, we discovered that returns which show as `NOT DUE YET` in the internal UI and aren't even listed in the external UI are included in the CSV templates generated.
These need to be excluded. So, this change adds 'end date' as a filter to the [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service/pull/2693) API …

Exclude not-ended rtns from generated CSV template

---

src/internal/modules/manage/lib/manage-nav.js
test/internal/modules/manage/lib/manage-nav.test.js

Spotted that when running the unit tests locally, the `manage-nav.test.js` would always fail. No doubt this is due to changes we've been making as we migrate legacy journeys that start from the Manage page to [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).
Initially, we thought it was because we hadn't stubbed the config properly. However, we then noticed that the `manage-nav.js` module was requiring the same configuration twice, using both standard and destructuring methods.
This change sorts the issue and gets the tests running again in all environments.

Fix failing unit tests

---

src/external/lib/connectors/services/returns/ReturnsApiClient.js
src/external/modules/returns/lib/helpers.js
src/internal/lib/return-path.js
test/internal/lib/return-path.test.js

https://eaflood.atlassian.net/browse/WATER-5128
When testing WATER-5117, our QA team was looking at a water company licence (03/28/38/0018) that had its quarterly return logs all set up for the current year. In this case, they have three return requirements, so three return logs have been generated per quarter. That means 12 in total for the period from April 1, 2025, to March 31, 2026.
Logging in as an external user on 30 June 2025, they found they could see the first batch of quarterly return logs (1 April to June 30), all with a status of 'NOT DUE YET'. This was not expected.
The reason is a faulty assumption in the logic that determines whether to show a return log. If a return log's end date is less than _or equal to_ the current date, it will show it. It should be just less than the …

Fix ext view returns showing 'not due yet' returns

---

src/shared/lib/connectors/services/water/CompaniesService.js
test/internal/modules/internal-search/controller.test.js

https://eaflood.atlassian.net/browse/WATER-5128
When testing WATER-5117, our QA team was looking at a water company licence (03/28/38/0018) that had its quarterly return logs all set up for the current year. In this case, they have three return requirements, so three return logs have been generated per quarter. That means 12 in total for the period from April 1, 2025, to March 31, 2026.
Logging in as an external user on 30 June 2025, they found they could see the first batch of quarterly return logs (1 April to June 30), all with a status of 'NOT DUE YET'. This was not expected.
The reason is a faulty assumption in the logic that determines whether to show a return log. If a return log's end date is less than _or equal to_ the current date, it will show it. It should be just less than the …

Fix CSV upload template inc. 'not due yet' returns

---

src/external/views/nunjucks/returns/upload-summary.njk

https://eaflood.atlassian.net/browse/WATER-5129
It has been noted that when we ask users to submit a return via the web, we display a disclaimer on the final page.
However, if they use the bulk upload route (uploading returns from a CSV), no such disclaimer is shown. We are now requesting that water companies submit their returns quarterly, and they are the largest users of the bulk upload route.
We've been asked to ensure that the same disclaimer is displayed on the bulk upload submit page.

Add disclaimer to bulk returns upload submit page

---

src/external/modules/content/routes.js
src/external/views/nunjucks/content/research-privacy-policy.njk

https://eaflood.atlassian.net/browse/WATER-5037
To initiate surveys and user research, a privacy policy is in place and being used for WRWA research. This privacy policy is currently hosted on a third-party website (Smart Survey).
We want the privacy policy to be hosted by the service to improve trust and confidence in its source.

Add external privacy policy for surveys

---

.github/workflows/ci.yml
.snyk

https://eaflood.atlassian.net/browse/WATER-5191
With the adoption of SSO in the Defra GitHub org, our current [Snyk](https://snyk.io) status checks have stopped working.
The [team issue](https://github.com/DEFRA/water-abstraction-team/issues/144) goes into more detail, but in essence, whilst the GitHub account that **Snyk** uses to connect has SSO enabled, it won't connect to GitHub to update the PR with the test result.
This change performs the same check without **Snyk** having to authenticate to GitHub. Instead, GitHub will authenticate with **Snyk** by using its CLI via a GitHub action.
It does mean **Snyk** will no longer be listed as a separate check; instead, it will just be a new step in our CI. So, the outcome (adding a package with a vulnerability will cause the PR to fail …

Switch to using Snyk CLI action in CI

---

.snyk

https://github.com/DEFRA/water-abstraction-team/issues/144
**Snyk** has identified that [tmp](https://github.com/raszi/node-tmp) has a [Symlink Attack vulnerability](https://security.snyk.io/vuln/SNYK-JS-TMP-11501554).
Unfortunately, it is introduced via [@hapi/scooter](https://github.com/hapijs/scooter), which hasn't been updated in more than 3 years, and is unlikely to be.
As this is an issue in the legacy code, the effort to find a replacement or resolve the issue puts it out of scope, hence we are adding an exception.

Add snyk exception for tmp

---

src/shared/lib/returns/badge.js
test/internal/modules/view-licences/controller.test.js

https://eaflood.atlassian.net/browse/WATER-5216
Currently when a return log is created it is automatically pre-populated with a due date. However, the process of assigning a due date to a return log is being updated so that the due date is not set on creation. Instead, it is set when the reminders are sent out.
This means that some new return logs will now have a null due date where previously the due date would always have been populated.
This PR will update the search results so that when searching for a return. The status of a return will display ‘Not Due Yet’ when the due date is not set and the status is "due".

Return search - Not due yet status
