.gitignore, etl/anonymise.js, etl/export.js, etl/index.js, etl/normalise.js, etl/package.json
Add a tool to import data from the NALD spreadsheet export into the permit repository API.
=> Add ETL tool

src/lib/VmL.js, src/views/index.js
Add a fix for the licence terms page and properly render all NGR points
=> Prototype v5 review

.gitignore, README.MD, src/lib/VmL.js
Remove the hardcoded values for the licence type ID and org ID from VML.js and pushed them into the .env file. Also updated the .gitignore file.
=> Remove hardcoded values

src/lib/VmL.js, src/sass/application.scss, src/views/index.js, src/views/partials/styles.html, src/views/water/licence.html, src/views/water/licences_terms.html
The authorisation data coming back from the permit repository had changed so I've changed the code reading this to make logins fail correctly.
The other changes are minor cosmetic ones.
=> Prorotype v5 test comments

src/lib/VmL.js, src/views/water/licence_error.html
=> resolve issue where service hangs when licence does not exist 

.gitignore, gulpfile.js, package.json, src/assets/sass/blocks/_table.scss
- Adds a watch task for the SASS building.
- Changes the table styles to include overflow auto to the
multiple-choice class to allow the element to have height.
=> bugfix/WATER-1044: Table styles when zoomed

src/assets/sass/blocks/_notification-preview.scss, src/modules/notifications/task-data.js, src/views/index.js
- Adds styles for sibling h1 and blockquote
- Adds an address mapper to force the address onto a line per address
part.
- Changes the handlebars markdown helper to replace the ^ with a >
character before render to deal with the notify specific markdown.
=> bugfix/WATER-1086: Notifications changes

src/views/water/register_email.html, src/views/water/register_send_again.html, src/views/water/reset-password/reset_password_change_password.html, src/views/water/reset-password/reset_password_get_link.html
https://eaflood.atlassian.net/browse/WATER-989
Fixed 4 incorrectly nested closing tags
=> Bugfix for IE11 grey footer issue

package-lock.json, src/assets/sass/blocks/_space.scss, src/modules/auth/controller.js, src/modules/auth/routes.js, src/views/partials/feedback-accessibility-message.html, src/views/partials/feedback-survey.html, src/views/water/auth/signed-out.html, src/views/water/content/accessibility.html, src/views/water/content/feedback.html, test/modules/auth/controller.js
Adds a page that the user is redirected to on sign out.
- Moves accessibility message into a partial
- Moves the survey into a partial
- Adds a test for the redirect after sing out.
- Update the accessibility page content taking into account the new
feature that is not entirely accessible.
=> WATER-1127: Feedback after sign out

src/views/partials/contact-details-addresses.html, src/views/partials/contact-details-name-and-role.html
WATER-1277
Adds partials for name and job title, and contact details ready for
future stories.
It may be that these change slightly when used.
=> Adds partials ready for entering contact details

src/views/partials/element-heading-large.html, src/views/water/licences-add/add-licences.html, src/views/water/registration/register_email.html, src/views/water/view-licences/licences.html
Fixes some html validation warnings that were suggested by an
accessibility report.
=> WATER-812: HTML Validation

package-lock.json, src/lib/user-data.js, src/lib/view.js, src/modules/contact-details/controller.js, src/modules/contact-details/routes.js, src/modules/notifications/contact-controller.js, src/modules/routes.js, src/views/partials/contact-details-addresses.html, src/views/partials/contact-details-name-and-role.html, src/views/water/contact-details/contact-information.html, test/modules/contact-details/controller.js
WATER-1125
Adds new module and routes for contact information
Adds controller tests
Adds error handling using form validator plugin
Fixes an indentation issue in the address textarea
Refactors to use user-data module
=> Allow a user to setup contact information

src/views/partials/error-summary-heading.html, src/views/partials/error-summary-link.html, src/views/water/contact-details/contact-information.html, src/views/water/notifications/contact-details.html, src/views/water/notifications/contact-name-job.html
=> Adds errors at top of page when capturing contact details

src/lib/connectors/idm.js
WATER-1309
Uses the updates IDM reset password resource which includes the
application name that the user is wanting to authenticate against.
=> Fix: Reset Password

src/modules/service-status/controller.js
Fixes the service status page. Assigns the correct data from the IDM kpi
resource.
=> Fix: Service status page

src/modules/returns/controller.js, src/modules/returns/external-routes.js, src/modules/returns/helpers.js
Adds route permissions to prevent an agent accessing a return that they
are not authorised to view.
=> Fix: Unauthorised agent access to return

src/modules/manage-licences/routes.js, src/views/water/manage-licences/manage_licences.html
Updates the content to the latest requirements.
=> Fix: Align manage access content

src/lib/connectors/idm.js, src/lib/connectors/notify.js, src/modules/manage-licences/controller.js, src/modules/reset-password/routes.js
WATER-1415
Also set bad_logins to zero after successful authentication.
=> Feat: Remove UTM params from some routes

src/modules/returns/routes/edit.js
Enables the returns plugin to populate the request with the required
data
=> Fix: Corrects external returns route config

src/views/water/returns/index.html
WATER-1392
Adds the purpose alias if available for an external user
=> Feat: Purpose alias

src/views/partials/return-header.html
=> Fix: Adds the purpose alias to the returns page

src/assets/sass/blocks/_badge.scss, src/views/partials/return-due-badge.html
=> Fix: Update colours and text for return due badge

.labrc.js, gulpfile.js, package-lock.json, package.json
WATER-1557
Updates to a version that does not have a recursive function that can be called in a way that never returns.
Also updates to Gulp V4 to remove some high security alerts.
=> Fix: Update airbrake js

gulpfile.js
Missed a couple of tasks when upgrading gulp to the latest version.
=> Fix: Gulp file not properly updated to V4

src/assets/sass/application.scss, src/assets/sass/blocks/_notification-report-table.scss, src/assets/sass/blocks/_notification-report.scss, src/assets/sass/blocks/_text.scss, src/views/partials/node.html, src/views/water/auth/signin.html, src/views/water/licences-add/select-address.html, src/views/water/notifications-report/index.html, src/views/water/notifications-report/view.html, src/views/water/reset-password/reset_password.html, src/views/water/returns/internal/submitted.html, src/views/water/view-licences/conditions.html, src/views/water/view-licences/gauging-station.html, src/views/water/view-licences/rename.html
WATER-1554
Removes inline styles which are not permitted by the CSP header. Some of
the styles could actually just be removed, and for others, new classes
have been made and used.
=> Fix: Handle inline style tags with CSP header

src/views/water/content/privacy_policy.html, src/views/water/registration/register_email.html
=> Feat: Updates the privacy policy

src/views/partials/footerjs.html, src/views/water/index.html
Adds a nonce tag to the script tag created by google analytics.
=> Fix: CSP warning from google tag manager

src/modules/view-licences/helpers.js, test/modules/view-licences/helpers.js
WATER-1620
Trims the search fields when a user is searching for a licence.
=> Fix: Trims search data

src/modules/add-licences/controller.js, src/modules/auth/controller.js, src/modules/manage-licences/controller.js, src/modules/reset-password/controller.js, src/modules/returns/controllers/edit.js, src/modules/returns/lib/session-helpers.js, src/modules/service-status/controller.js
This gives better detail at Errbit
=> Feat: Use logger instead of request.log for errors

src/lib/connectors/permit.js, src/lib/connectors/water-service/licences.js, src/modules/abstraction-reform/controllers/edit.js, src/modules/abstraction-reform/lib/form-generator.js, test/modules/abstraction-reform/lib/form-generator.js
Resolves conditions and points data by calling the water service licence
resources.
Basic information is mapped from the response to drive a drop down list.
=> Feat: Resolve licence data in JSON schema

gulpfile.js, package-lock.json, package.json, src/assets/sass/application.scss, src/views/partials/feedback-survey-item.html, src/views/partials/feedback-survey.html
WATER-1723
Uses iframe-resizer in partnership with the survey content so that the
iframe is resized to fit its contents.
=> Feat: Updates survey to resize iframe

package-lock.json, src/modules/abstraction-reform/schema/wr22/2.9.1.json, src/modules/abstraction-reform/schema/wr22/2.9.2.json, src/modules/abstraction-reform/schema/wr22/2.9.3.json, src/modules/abstraction-reform/schema/wr22/2.9.4.json, src/modules/abstraction-reform/schema/wr22/2.9.5.json, src/modules/abstraction-reform/schema/wr22/2.9.6.json, src/modules/abstraction-reform/schema/wr22/2.9.7.json, src/modules/abstraction-reform/schema/wr22/2.9.8.json, src/views/nunjucks/abstraction-reform/edit-data.njk, src/views/nunjucks/abstraction-reform/licence.njk, src/views/nunjucks/abstraction-reform/macros/2.9.4.njk, src/views/nunjucks/abstraction-reform/macros/2.9.8.njk, src/views/nunjucks/abstraction-reform/macros/index.njk, src/views/nunjucks/abstraction-reform/select-schema.njk, test/modules/returns/lib/helpers.js
WATER-1817
Adds the Anglian HOF conditions
=> Feat: Adds Anglian HOF conditions

src/modules/abstraction-reform/schema/wr22/2.9.4.json, src/modules/abstraction-reform/schema/wr22/2.9.8.json
=> Fix: Corrects the error text for Anglian conditions

package-lock.json, package.json, src/assets/sass/v2/application.scss, src/assets/sass/v2/blocks/_link.scss, src/assets/sass/v2/blocks/_phone.scss, src/assets/sass/v2/blocks/_search.scss, src/lib/view-engine/nunjucks.js, src/lib/view/main-nav.js, src/modules/internal-search/controller.js, src/modules/internal-search/lib/redirect-to-return.js, src/modules/returns/routes/edit-internal.js, src/modules/returns/routes/internal.js, src/views/nunjucks/internal-search/index.njk, src/views/nunjucks/macros/forms/search.njk, src/views/nunjucks/macros/paginate.njk, test/modules/internal-search/lib/redirect-to-return.js
- IE11 bug on pagination
- Some return IDs give blank screen
- Search results optimised for mobile
- Search button wrong size/position on mobile
- Favicon missing on Nunjucks pages
- Rename first tab to "Licences" and highlight on internal return flows
=> Fix issues in internal search

package-lock.json, package.json, src/lib/connectors/water-service/licences.js
- Removes some duplicate error handling which will be dealt with by the
catch block.
- Also updates HAPI to 17.8.3
=> WATER-1833

src/views/water/content/accessibility.html
WATER-1829
Removes accessibility context regarding survey not being accessible
because it now is.
=> Fix: Removes superfluous accessibility text

package-lock.json, src/lib/connectors/service-request.js, src/lib/connectors/water-service/licences.js, test/lib/connectors/water-service/licences.js
Fixes an issue with the service request module where a promise was not
being returned.
=> Fix: Ensure ServiceRequest returns a promise

src/modules/returns/lib/return-path.js
=> Update returnId to use getReturnId

src/views/nunjucks/returns/confirm.njk, src/views/nunjucks/returns/macros/return-header.njk, test/modules/returns/lib/return-helpers.js
bugfix/WATER-2019
Fix in Returns header caused alignment issues on Confirm page, so added govuk-grid-rows divs on cofirm page so both pages are properly formatted
=> Fix alignment on 'Have you abstracted water?' page

src/modules/returns/lib/return-helpers.js, test/modules/returns/controllers/internal.js, test/modules/returns/lib/return-helpers.js
WATER-2023
Fixes a few issues with date formats and missing data in the final
returns object. This was caused by missing logic in some of the apply
functions where the internal and external flows now differ.
=> Fix: Fixes issues submitting internal returns

src/views/nunjucks/returns/nil-return.njk
=> Fix: Fixes the markup for the nil return page

src/assets/sass/blocks/_badge.scss, src/assets/sass/v2/blocks/_badge.scss, src/modules/returns/controllers/view.js, src/modules/returns/lib/helpers.js, src/views/nunjucks/macros/badge.njk, src/views/partials/return-due-badge.html, src/views/water/returns/index.html, test/modules/returns/lib/helpers.js
WATER-2033
Swaps the order of the Site description and purpose columns in the
returns view.
Updates the badge styles.
=> Fix: Updates column order and badge styles

src/assets/sass/v2/blocks/_badge.scss
Missed this one out when adding the style for the due badge.
=> Fix: Adds missing due badge style

package-lock.json, src/modules/returns/forms/amounts.js, src/modules/returns/forms/confirm.js, src/modules/returns/forms/log-receipt.js, src/modules/returns/forms/meter-details.js, src/modules/returns/forms/meter-readings.js, src/modules/returns/forms/meter-used.js, src/modules/returns/forms/quantities.js, src/modules/returns/forms/single-total.js, src/modules/returns/forms/units-factory.js, src/modules/returns/forms/units.js, src/modules/returns/routes/edit-internal.js, src/views/nunjucks/returns/confirm.njk, src/views/nunjucks/returns/macros/confirm-page-inset-text.njk, src/views/nunjucks/returns/macros/return-header.njk, src/views/nunjucks/returns/macros/return-quantities-table.njk, src/views/nunjucks/returns/submitted.njk, src/views/partials/form-date.html, src/views/partials/return-header.html, test/modules/returns/forms/amounts.js, test/modules/returns/forms/meter-readings.js, test/modules/returns/forms/meter-used.js, test/modules/returns/forms/quantities.js
WATER-2039
Update form label and hint text dynamically based on isInternal flag. Fix nunjucks internal returns header.
=> Fix: Internal returns flow content fixes

src/assets/sass/v2/application.scss, src/assets/sass/v2/blocks/_spinner.scss, src/modules/returns/controllers/upload.js, src/views/nunjucks/waiting/index.njk, test/modules/returns/controllers/upload.js
WATER-2109
Create styling for spinner. Update nunjucks page to include new style. Fix issue with upload controller, waiting page was being displayed in the wrong function.
=> Fix: Centre align spinner on waiting page

src/modules/abstraction-reform/forms/select-schema.js, src/modules/abstraction-reform/lib/schema-helpers.js, src/modules/abstraction-reform/schema/wr22/1.x.json, src/modules/abstraction-reform/schema/wr22/10.x.json, src/modules/abstraction-reform/schema/wr22/11.x.json, src/modules/abstraction-reform/schema/wr22/12.x.json, src/modules/abstraction-reform/schema/wr22/13.x.json, src/modules/abstraction-reform/schema/wr22/14.x.json, src/modules/abstraction-reform/schema/wr22/15.x.json, src/modules/abstraction-reform/schema/wr22/16.x.json, src/modules/abstraction-reform/schema/wr22/17.x.json, src/modules/abstraction-reform/schema/wr22/18.x.json, src/modules/abstraction-reform/schema/wr22/19.x.json, src/modules/abstraction-reform/schema/wr22/2.x.json, src/modules/abstraction-reform/schema/wr22/20.x.json, src/modules/abstraction-reform/schema/wr22/21.x.json, src/modules/abstraction-reform/schema/wr22/22.x.json, src/modules/abstraction-reform/schema/wr22/23.x.json, src/modules/abstraction-reform/schema/wr22/24.x.json, src/modules/abstraction-reform/schema/wr22/25.x.json, src/modules/abstraction-reform/schema/wr22/3.x.json, src/modules/abstraction-reform/schema/wr22/4.x.json, src/modules/abstraction-reform/schema/wr22/5.x.json, src/modules/abstraction-reform/schema/wr22/6.x.json, src/modules/abstraction-reform/schema/wr22/7.x.json, src/modules/abstraction-reform/schema/wr22/8.x.json, src/modules/abstraction-reform/schema/wr22/9.x.json, test/modules/abstraction-reform/forms/select-schema.js
WATER-2106
Create schema file for bespoke condition (ending in '.x'). Add function to sort schema to display the bespoke condition at the bottom of radio button list.
=> Add bespoke condition for each schema category

package-lock.json, src/modules/abstraction-reform/schema/wr22/2.3.json, src/modules/abstraction-reform/schema/wr22/2.5.json, src/modules/abstraction-reform/schema/wr22/2.6.json, src/modules/abstraction-reform/schema/wr22/2.7.json, src/modules/abstraction-reform/schema/wr22/2.8.json
WATER-2115
Adds "m³/d" and "Ml/d" to some licence flow conditions.
=> Feat: Adds extra units to licence conditions

.eslintignore, package-lock.json, package.json, src/lib/connectors/crm/verification.js, src/lib/connectors/service-request.js, src/lib/licence-transformer/csv-transformer.js, src/lib/logger/vendor/winston-airbrake.js, src/lib/view-engine/filters/abstraction-reform.js, src/modules/abstraction-reform/lib/action-creators.js, src/modules/abstraction-reform/lib/licence-helpers.js, src/modules/abstraction-reform/lib/report-helpers.js, src/modules/abstraction-reform/lib/search.js, src/modules/auth/forms/select-company.js, src/modules/view-licences/base.js, test/lib/connectors/water-service/returns.js, test/lib/view-engine/filters/abstraction-reform.js
Adds the correct ignore file and updates the npm task to lint the
expected files.
=> Chore: Makes eslint work better

package-lock.json, src/external/views/nunjucks/internal-search/user-status.njk, src/internal/views/nunjucks/internal-search/user-status.njk
WATER-2141
Changed govuk-grid-column div to full width from two-thirds-width on user status page
=> Fix: Content on User Status page now full column width

src/internal/views/nunjucks/internal-search/macros/user-details.njk
=> Fix: Make user-status heading 2/3 width and smaller text

src/shared/plugins/user-journey/index.js, test/shared/lib/plugins/user-journey/index.js
WATER-2166
Also reduces the number of page transitions to 20 from 50.
=> Fix: Don't track user journey on non authed routes

.gitignore, package-lock.json, package.json, src/internal/lib/view-licence-config.js
WATER-2217
Updates the internal view-licence-config to fix the function context for
the exported `getRivelLevel` function.
=> Fix: Fixes internal view of gauging stations

src/internal/modules/account/controller.js, src/internal/modules/account/forms/create-user.js, src/internal/modules/account/forms/set-permissions.js, src/internal/modules/account/routes.js, src/internal/modules/routes.js, src/internal/views/nunjucks/account/create-user-success.njk, src/internal/views/nunjucks/account/create-user.njk, src/internal/views/nunjucks/account/set-permissions.njk, test/internal/modules/account/controller.js, test/internal/modules/account/forms/create-user.js, test/internal/modules/account/forms/set-permissions.js
WATER-2227
Adds the UI component of the larger feature to allow an internal user to
create other internal users and assign a set of permissions.
=> Feat: Adds the UI for adding an internal user

src/internal/modules/account/controller.js, src/shared/lib/connectors/services/idm/UsersApiClient.js, test/internal/modules/account/controller.js, test/shared/lib/connectors/services/idm/UsersApiClient.js
Also handle error when user exists on set permissions page in add user flow.
=> Fix issue where new user could not be created.

src/internal/lib/permissions.js, src/internal/modules/account/controller.js, src/internal/modules/account/forms/set-permissions.js, src/internal/modules/internal-search/controller.js, src/internal/modules/internal-search/routes.js, src/internal/views/nunjucks/internal-search/update-permissions-success.njk, src/internal/views/nunjucks/internal-search/user-status.njk, src/shared/lib/connectors/services/water/UsersService.js, test/internal/lib/permissions.js, test/internal/modules/account/controller.js, test/internal/modules/account/forms/set-permissions.js, test/internal/modules/internal-search/controller.js, test/shared/lib/connectors/services/water/UsersService.js, test/shared/responses/water-service/user/_userId_/status/index.js
WATER-2183
Add permissions form to user-status page. Create update-permissions-success.njk page. Add connector to water service endpoint. Add routes and controller functions for post and get requests.
=> Feat: Amend internal user permissions

package-lock.json, src/internal/modules/view-licences/controller.js, src/internal/modules/view-licences/routes.js, src/internal/views/nunjucks/view-licences/expired-licence.njk, test/internal/modules/view-licences/controller.js
WATER-2290
Displays the 'Charge' tab to an authorised user on the expired licences
page.
=> Feat: Show charge versions for expired licences

data/condition_titles.csv
WATER-2297
Adds the missing clause and sorts the CSV contents to ease comparison
with the NALD_LIC_COND_TYPES table.
=> Fix: Adds missing derogation clause

src/external/views/nunjucks/content/cookies.njk, src/internal/views/nunjucks/content/cookies.njk
WATER-2234
Update content on internal and external cookie page.
=> Update cookie policy

src/external/lib/hapi-plugins/index.js, src/internal/lib/hapi-plugins/index.js
=> Fix: Adds missing route for CSP report

src/internal/views/nunjucks/view-licences/conditions.njk
=> Fix: Removes duplicate conditions message

.snyk, package-lock.json, package.json, src/external/modules/returns/controllers/upload.js, src/external/modules/returns/lib/csv-templates.js, test/external/modules/returns/controllers/upload.js
Upgrades the CSV parse library to 4.x
Also minor fixes in returns CSV functionality.
=> Upgrade csv-parse library to 4.x

src/internal/views/nunjucks/billing/batch-invoice.njk, src/shared/assets/sass/blocks/_table.scss
Feat/WATER-2387
-- design fixes to the nunjucks file
=> Design changes to UI for invoice view

src/internal/lib/connectors/services/water/BillingBatchService.js, src/internal/modules/billing/controller.js, test/internal/lib/connectors/services/water/BillingBatchService.js, test/internal/modules/billing/controller.js
=> Feat: Wire up approval of bill runs

src/internal/modules/billing/controller.js, test/internal/modules/billing/controller.js
WATER-2514
Update batch status.
Fix tariff spelling errors.
=> Update batch status from complete to ready

src/internal/modules/billing/controller.js, src/internal/modules/billing/pre-handlers.js, src/internal/modules/billing/routes.js, src/internal/views/nunjucks/billing/batch-exist.njk, test/internal/modules/billing/controller.js, test/internal/modules/billing/pre-handlers.js, test/internal/modules/billing/routes.js
WATER-2510
Adds the content for the page shown if the user attempts to create a new
batch for a region where there is already a batch being processed.
=> Feat: Adds content for batch conflict page

src/internal/modules/billing/controller.js, src/internal/views/nunjucks/billing/batch-list.njk, test/internal/modules/billing/controller.js
Feat/water-2523
--billing getBatchList updated to use totals from  water service api
-- tests updated to use new data model
-- batch list view updated to use the new data model and charge filter
=> Update Billing batch list UI with totals from backend

src/internal/modules/billing/controller.js, src/internal/views/nunjucks/billing/batch-list.njk, src/shared/view/nunjucks/filters/charge.js, test/internal/modules/billing/controller.js, test/shared/view/nunjucks/filters/charge.js
Fixes issues in the billing batch list view:
- Hides table if no batches
- Handles case where totals are not available for a batch
- Corrects spelling of 'Building' for batch label
=> Batch list view fixes

src/internal/modules/billing/services/batch-service.js, test/internal/modules/billing/controller.js
bug-fix/water-2448
-- invoice data shape received from the water service changed
-- tests updated
=> Fix - Delete a customer from a bill run

src/internal/modules/billing/controller.js, src/internal/modules/waiting/controller.js, test/internal/modules/billing/controller.js, test/internal/modules/waiting/controller.js
--changes to use event.id instead of event_id
=> bug-fix/events-for-billing

src/internal/lib/view-engine/filters/index.js, src/internal/views/nunjucks/billing/batch-list.njk, src/internal/views/nunjucks/billing/batch-summary.njk, src/internal/views/nunjucks/billing/macros/totals.njk, src/shared/lib/number-formatter.js, src/shared/view/nunjucks/filters/default-to.js, test/shared/lib/number-formatter.js, test/shared/view/nunjucks/filters/default-to.js
WATER-2555
Updates the batch summary and list to show a dash in the event that the
batch totals have not been refreshed
=> Feat: Batch total display when totals not obtained

src/external/views/nunjucks/add-licences/verification-sent.njk, src/internal/views/nunjucks/add-licences/verification-sent.njk
feat/water-2591
-- text changes to add a licence security code sent page
=> Postal text changes to adding a licence

src/internal/modules/billing/controllers/bill-run.js, src/internal/modules/billing/forms/billing-region.js, src/internal/modules/billing/forms/billing-type.js, src/internal/modules/billing/lib/bill-run-types.js, src/internal/modules/billing/lib/seasons.js, src/internal/modules/billing/routes/bill-run.js, src/shared/view/nunjucks/macros/forms/radio.njk, test/internal/lib/connectors/services/water/BillingBatchService.js, test/internal/modules/billing/controllers/bill-run.js, test/internal/modules/billing/forms/billing-region.js, test/internal/modules/billing/forms/billing-type.js, test/internal/modules/billing/routes/bill-run.js
WATER-2611
UI work to add the season as an extra field if the user chooses a two
part tariff bill run.
=> Feat: Add season to tpt bill run in the UI

src/internal/views/nunjucks/billing/macros/invoice-metadata.njk
Fixes issue when displaying multiple licences on confirm invoice removal page
=> UI tweaks to confirm invoice removal page

src/shared/lib/logger-factory.js, test/shared/lib/logger-factory.js
WATER-2724
Improves the logging of request details to help identity an unexpected
options request in the error logs
=> Feat: Include href in logged request details

src/internal/views/nunjucks/charging/charge-version.njk, src/internal/views/nunjucks/view-licences/tabs/charge.njk, src/shared/view/nunjucks/filters/charge-element-abstraction-period.js, test/shared/view/nunjucks/filters/charge-element-abstraction-period.js
WATER-2747
Updates the templates to handle the updated shape of data returned from
the water service.
Dependent on https://github.com/DEFRA/water-abstraction-service/pull/1097
=> Feat: Use updated charge versions api

src/internal/modules/billing/lib/mappers.js, src/internal/modules/billing/pre-handlers.js, src/internal/views/nunjucks/billing/batch-invoice.njk, src/internal/views/nunjucks/billing/macros/transactions-table.njk, test/internal/modules/billing/lib/mappers.js
Adds flag to retrieve batch totals in billing pre-handlers
=> Fixes charge element totals on invoice summary view

package-lock.json, src/internal/modules/charge-information/controller.js, src/internal/modules/charge-information/forms/billing-account.js, src/internal/modules/charge-information/forms/index.js, src/internal/modules/charge-information/forms/reason.js, src/internal/modules/charge-information/forms/use-abstraction-data.js, src/internal/modules/charge-information/lib/actions.js, src/internal/modules/charge-information/lib/helpers.js, src/internal/modules/charge-information/lib/reducer.js, src/internal/modules/charge-information/lib/routing.js, src/internal/modules/charge-information/pre-handlers.js, src/internal/modules/charge-information/routes.js, src/internal/views/nunjucks/charge-information/check.njk, src/internal/views/nunjucks/view-licences/tabs/charge.njk, src/shared/lib/connectors/services/water/ChargeVersionsService.js, src/shared/lib/connectors/services/water/LicencesService.js, src/shared/view/nunjucks/filters/form.js, test/internal/modules/charge-information/controller.js, test/internal/modules/charge-information/forms/billing-account.js, test/internal/modules/charge-information/forms/use-abstraction-data.js, test/internal/modules/charge-information/lib/actions.js, test/internal/modules/charge-information/lib/helpers.js, test/internal/modules/charge-information/lib/reducer.js, test/internal/modules/charge-information/lib/routing.js, test/internal/modules/charge-information/pre-handlers.js, test/internal/modules/charge-information/routes.js, test/internal/test-helpers.js, test/shared/lib/connectors/services/water/ChargeVersionsService.js, test/shared/lib/connectors/services/water/LicencesService.js
WATER-2740
- Updates the reasons page to redirect to the start date form
- Adds the non chargeable option to the reasons page
- Updates shared licence service to get licence versions
- Get default charges for licence version
- Updates routing for new routes
- Updates the reducer
- Updates getDefaultView in helpers
- Adds new actions and tests
- Adds new template for check information page
- Adds pre handler to load default charges for licence
- Adds new forms
- New routes for the flow pages
- Updates the controller
- Adds the billing accounts
=> Feat: Basic charge information flow

src/internal/lib/constants.js, src/internal/modules/agreements/pre-handlers.js, src/internal/modules/agreements/routes.js, src/internal/views/nunjucks/agreements/delete.njk, src/internal/views/nunjucks/view-licences/tabs/charge.njk, src/shared/lib/mappers/agreements.js, src/shared/plugins/view-licence/controller.js, test/internal/modules/agreements/pre-handlers.js, test/internal/modules/agreements/routes.js, test/shared/plugins/view-licence/controller.js
WATER-2688
* Supports new shape of data returned from water service
* Ensures agreement descriptions are displayed on list view page
* Supports new IDM roles for managing/deleting agreements
=> Supports new agreements data structure and IDM roles

src/internal/modules/charge-information/controllers/charge-element.js, src/internal/modules/charge-information/forms/charge-element/loss-category.js, src/internal/modules/charge-information/forms/charge-element/quantities.js
bugfix/water-2803
-- hints were missing when form errors for season and loss
--select a loss category error message corrected
-- quantities form Joi validation added for greater than zero
=> Bug fixes for WATER-2803

src/external/lib/view-licence-config.js, src/shared/plugins/view-licence/controller.js
Fixes issue where agreements being loaded for external users caused permission error
=> Fixes issue with agreements permissions for external users

package.json, src/internal/modules/agreements/forms/end-agreement.js
https://eaflood.atlassian.net/browse/WATER-2777
=> Corrected validation messages following QA feedback

src/internal/modules/charge-information/pre-handlers.js, test/internal/modules/charge-information/pre-handlers.js
bugfix/water-2689
-- Charge change reasons now sorted in alphabetical order
=> Bugfix - Charge info pre handler change reasons alphabetical sort added 

src/internal/modules/contact-entry/controllers.js, src/internal/modules/contact-entry/forms/company-search-select-company.js, src/internal/modules/contact-entry/forms/company-search.js, src/internal/modules/contact-entry/forms/select-account-type.js, src/internal/modules/invoice-accounts/forms/select-existing-company.js, src/internal/views/nunjucks/contact-entry/select-company.njk, test/internal/modules/contact-entry/controllers.js
In response to: https://eaflood.atlassian.net/browse/WATER-2837?focusedCommentId=247488
=> UI Corrections following QA feedback

src/internal/modules/charge-information/forms/start-date.js, src/internal/modules/charge-information/pre-handlers.js, test/internal/modules/charge-information/pre-handlers.js
Bugfix/water 2689
-- when custom effective date selected make custom date Joi.required()
=> Bigfix - Effective custom date is required

src/internal/lib/licence-data-config.js, test/internal/lib/licence-data-config.js
Fixes issue where envelope of charge version workflow API response not parsed correctly
=> Charge version workflow API / scope bug

src/shared/lib/connectors/services/water/CompaniesService.js
WATER-2913
Fixes an issue caused by sending extra data to the company returns
endpoint due to spreading an object's properties.
=> Fix: Fixes an issue getting bulk returns template

src/internal/modules/address-entry/routes.js
Ticket: https://eaflood.atlassian.net/browse/WATER-2931
=> Allows the use of the address-entry plugin in production

src/internal/views/nunjucks/internal-search/macros/user-details.njk
=> Bugfix: Show date user account is removed on user status page

src/internal/views/nunjucks/charge-information/view.njk, src/internal/views/nunjucks/view-licences/tabs/charge.njk, src/shared/plugins/view-licence/controller.js
* Sorts charge versions by start date then version number
* Adds the change reason text to the table
* Hide invoice account/company info for non-chargeable charge versions
=> Charge information tab fixes

src/internal/modules/agreements/controller.js, src/internal/modules/agreements/forms/date-signed.js, src/internal/modules/agreements/lib/actions.js, src/internal/modules/agreements/lib/descriptions.js, src/internal/modules/agreements/lib/reducer.js, src/internal/views/nunjucks/agreements/check-start-date.njk, test/internal/modules/agreements/controller.js, test/internal/modules/agreements/lib/reducer.js
WATER-2883
* Updates date signed form
* Updates reducer to store date signed correctly when being overwritten
* Removes redundant file with agreement descriptions
=> Update: Make date signed optional in add agreement flow

src/internal/modules/billing/services/transactions-csv.js, test/internal/modules/billing/services/transactions-csv.js
WATER-2850
* Updates transaction mapping to csv rows
* Maps undefined values to blank cells in rows
=> Feat: Update bill run CSV download to handle min charge transactions

src/internal/modules/view-licences/controller.js, src/internal/modules/view-licences/routes.js, test/internal/modules/view-licences/controller.js
=> Bugfix: Remove charge info tab from expired licence summary

src/internal/modules/billing/services/transactions-csv.js, test/internal/modules/billing/services/transactions-csv.js
=> Bugfix: Show error in csv where txn value not calculated

src/internal/modules/view-licences/controller.js, test/internal/modules/view-licences/controller.js
=> Bugfix: Adds back link to expired licence page

src/internal/modules/billing/forms/two-part-tariff-quantity.js, src/internal/modules/charge-information/forms/charge-element/quantities.js, src/internal/modules/charge-information/lib/charge-elements/mappers.js, src/shared/view/nunjucks/filters/form.js, src/shared/view/nunjucks/macros/forms/text.njk, test/internal/modules/charge-information/controllers/charge-element.js, test/internal/modules/charge-information/forms/charge-elements/quantities.js, test/internal/modules/charge-information/lib/charge-elements/mappers.js, test/shared/view/nunjucks/filters/form.js, test/shared/view/nunjucks/filters/test-helpers.js
WATER-2937
* Adds hint text to billing quantity in TPT review
* Adds hint to quantities page in charge info flow
* Updates suffix mapping to use new feature in textInput macro
=> Bugfix: Limit volumes to 6 decimal places

src/external/config.js
feat/water2890
-- external user session timeout reduced from 1 day to 2 hours
=> External User session time out set to 2 hours

src/internal/modules/charge-information/controllers/view-charge-information.js, src/internal/modules/charge-information/lib/helpers.js, src/internal/views/nunjucks/charge-information/view.njk, test/internal/modules/charge-information/controllers/view-charge-information.js, test/internal/modules/charge-information/lib/helpers.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-2996
=> Bugfix/water 2996 - Minor UI fix for Charge Version Workflow

src/internal/modules/billing-accounts/controllers/billing-accounts.js, src/internal/modules/billing-accounts/plugin.js, test/internal/modules/billing-accounts/controllers/billing-accounts.js
Fixes data validation issue with handover to billing account plugin for update address flow.
=> Fix issue with validation of data supplied to billing account plugin

src/internal/modules/billing-accounts/forms/select-account.js
Following discussion with CB on `WATER-2915`
=> Small content change to billing account flow

src/internal/views/nunjucks/billing/batch-invoice.njk
=> WATER-3008: Update batch-invoice.njk

src/internal/views/nunjucks/charge-information/workflow-tabs/review.njk, src/internal/views/nunjucks/charge-information/workflow-tabs/to-set-up.njk
WATER-3006
* Updates date formats in To set up and Review tabs on charge info workflow page
=> Bugfix: Updates dates in charge info workflow to GDS format

src/internal/modules/charge-information/routes/charge-information.js
bugfix/use-abstraction-data-form-validation
-- route fixed to expect correct query params
=> Bugfix - charge info flow abstraction data route fixed

package-lock.json, package.json, src/internal/modules/billing/lib/mappers.js, src/internal/modules/billing/services/batch-service.js, src/internal/modules/billing/services/transactions-csv.js, src/internal/views/nunjucks/billing/batch-invoice.njk, src/internal/views/nunjucks/billing/batch-list.njk, src/internal/views/nunjucks/billing/batch-summary.njk, src/internal/views/nunjucks/billing/macros/invoice-metadata.njk, src/internal/views/nunjucks/billing/macros/invoices-table.njk, test/internal/modules/billing/controllers/bill-run.js, test/internal/modules/billing/lib/mappers.js, test/internal/modules/billing/services/transactions-csv.js
`WATER-3016`
Tweaks UI to accept new shape of data from water service for charging.
=> WATER-3016 store CM data/transactions in DB

package-lock.json, package.json, src/shared/plugins/cookie-message/index.js, src/shared/plugins/cookie-message/lib/cookie-domain.js, test/shared/plugins/cookie-message/index.js, test/shared/plugins/cookie-message/lib/cookie-domain.js
Fix domain issue when clearing GA cookies
=> Fix issue with analytics cookie domain

src/shared/plugins/cookie-message/routes.js, test/shared/plugins/cookie-message/routes.js
=> Tweak validation

cypress/integration/internal/bills-tab.spec.js
Relates to https://eaflood.atlassian.net/browse/WATER-3197
and https://eaflood.atlassian.net/browse/WATER-3196
=> Fixes test case

src/internal/modules/internal-search/controller.js, src/internal/modules/internal-search/lib/api-response-mapper.js, src/internal/modules/internal-search/lib/redirect-to-billing-account.js, src/shared/lib/billing-accounts/validators.js, test/internal/modules/internal-search/controller.js, test/internal/modules/internal-search/lib/redirect-to-billing-account.js
CRM PR: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/806
UI PR: https://github.com/DEFRA/water-abstraction-ui/pull/1776
Service PR: https://github.com/DEFRA/water-abstraction-service/pull/1417
Original ticket: https://eaflood.atlassian.net/browse/WATER-3203
=> Adds search functionality for billing accounts

src/internal/modules/abstraction-reform/lib/form-generator.js, test/internal/modules/abstraction-reform/lib/form-generator.js
=> Fixes issue where Digitise! autocomplete controls only showed 1 item

src/shared/public/javascripts/back-link.js
Reverts DEFRA/water-abstraction-ui#1780
=> Revert "Only use window.history.back if no link is provided"

cypress/integration/external/login.spec.js, cypress/integration/external/view-licences.spec.js, cypress/integration/internal/annual-bills-run.spec.js, cypress/integration/internal/bills-tab.spec.js, cypress/integration/internal/searchForLicence.spec.js, cypress/integration/internal/supplementary-bills-run.spec.js, cypress/integration/internal/two-part-tariff-bill-run.spec.js, src/external/modules/manage-licences/routes.js, src/external/modules/returns/forms/upload.js, src/external/views/nunjucks/add-licences/select-licences-error.njk, src/external/views/nunjucks/auth/signed-out.njk, src/external/views/nunjucks/layout.njk, src/external/views/nunjucks/returns/macros/return-declaration.njk, src/internal/modules/billing/controllers/two-part-tariff.js, src/internal/modules/returns/forms/single-total.js, src/internal/views/nunjucks/abstraction-reform/delete.njk, src/internal/views/nunjucks/auth/signed-out.njk, src/internal/views/nunjucks/billing-accounts/check-answers.njk, src/internal/views/nunjucks/layout.njk, src/internal/views/nunjucks/notifications/preview.njk, src/internal/views/nunjucks/returns-notifications/forms-confirm.njk, src/shared/plugins/auth/controller.js, test/external/modules/returns/lib/upload-helpers.js, test/internal/modules/billing/controllers/two-part-tariff.js, test/shared/lib/plugins/auth/controller.js
Relates to https://eaflood.atlassian.net/browse/WATER-3243
=> Changes "You are" to "You're"

src/external/config.js, src/external/modules/content/routes.js, src/external/views/nunjucks/content/accessibility.njk, src/internal/config.js, src/internal/modules/content/routes.js, src/internal/views/nunjucks/content/accessibility.njk
Changes link in accessibility page from GOV.uk guidance page to service homepage
=> Fix URL in accessibility page

cypress/fixtures/users.json, cypress/integration/external/externaluser-sharing-access.spec.js, cypress/integration/external/sharing-access-with-existing-user.spec.js, cypress/integration/external/sharing-access-with-new-user.spec.js
This PR is for the story  - https://eaflood.atlassian.net/browse/WATER-3219 
Here we have tests for the user journeys where existing user shares their licences with an existing user and also with a new user
=> Regression test/water 3219 - Sharing licence with existing and new user

cypress/integration/internal/update-view-returns-status-associated-to-a-licence.spec.js, cypress/integration/internal/update-view-returns-status-of-a-licence.spec.js
This Automated Regression test updates and verifies the below status 
User returns status - 
- Due 
- Completed 
- Received ( Updates from overdue to Received)
- Overdue 
- Void
=> Regression test/water 3231

package-lock.json, package.json
This PR Upgrades the cypress to the latest version 8.0 
Jira - WATER-3280
=> cypress upgraded to 8.0 - WATER-3280

cypress/integration/external/user-submitting-returns.spec.js, src/external/modules/returns/forms/amounts.js, src/external/modules/returns/forms/meter-reset.js, src/shared/modules/returns/forms/quantities.js, src/shared/modules/returns/models/Lines.js
Bugfix/external submit returns
This fixes joi validation errors for the external returns flow and the regression pack
=> Joi Validation Fix - submit external returns 

cypress/integration/external/user-submitting-returns.spec.js, src/external/modules/returns/forms/amounts.js, src/external/modules/returns/forms/meter-reset.js, src/shared/modules/returns/forms/quantities.js, src/shared/modules/returns/models/Lines.js
Bugfix/external submit returns
This is a duplicate PR that was approved and merged in to dev. This PR is to merge the fixes into the release branch
=> Dulpicate PR for Joi Validation Fix - submit external returns

src/external/modules/add-licences/controller.js, src/external/modules/manage-licences/controller.js, src/shared/lib/validators.js, test/external/modules/add-licences/controller.js, test/external/modules/manage-licences/controller.js, test/shared/lib/validators.js
This fixes the last few issues for the current regression tests for external users
-- add a licence flow fixed
-- give external user permission to access licence
-- fix for custom password validator (Thanks for you help with this one https://github.com/uijim)
=> Joi bug fixes for all external regression tests

src/external/modules/add-licences/controller.js, src/external/modules/manage-licences/controller.js, src/shared/lib/validators.js, test/external/modules/add-licences/controller.js, test/external/modules/manage-licences/controller.js, test/shared/lib/validators.js
Bugfix/joi fixes for external regression tests
=> Duplicate PR to merge Joi fixes for external regression tests to release branch

cypress/integration/internal/annual-bills-run.spec.js, cypress/integration/internal/two-part-tariff-bill-run.spec.js
bugfix/regression-bill-runs
-- annual and 2PT bill run regression tests fixed
=> Fixes regression test bill runs

cypress/integration/internal/annual-bills-run.spec.js, cypress/integration/internal/two-part-tariff-bill-run.spec.js
=> duplicate PR for fixes on bill run regression tests

package-lock.json, src/internal/modules/billing/controllers/two-part-tariff.js, src/internal/views/nunjucks/billing/two-part-tariff-quantities.njk, test/internal/modules/billing/controllers/two-part-tariff.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3273
=> Fixes an issue whereby charge period is not displaying in billing

src/internal/modules/billing/services/transactions-csv.js, test/internal/modules/billing/services/transactions-csv.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3275
=> Makes the bill number column appear, always

src/internal/modules/charge-information/forms/start-date.js, test/internal/modules/charge-information/controllers/charge-information.js, test/internal/modules/charge-information/controllers/non-chargeable.js, test/internal/modules/charge-information/forms/start-date.js
Following https://eaflood.atlassian.net/browse/WATER-3274
Russell requested that the UI should exhibit the same limit/behaviour.
=> Updates behaviour as requested by PO

src/shared/lib/forms/validationAdapters/json-schema.js, test/shared/lib/forms/validationAdapters/json-schema.js
Workaround for https://eaflood.atlassian.net/browse/WATER-3284
=> Inserts fudge

src/internal/modules/charge-information/forms/charge-element/abstraction-period.js, src/internal/modules/charge-information/forms/charge-element/agreements.js, src/internal/modules/charge-information/forms/charge-element/description.js, src/internal/modules/charge-information/forms/charge-element/loss-category.js, src/internal/modules/charge-information/forms/charge-element/purpose.js, src/internal/modules/charge-information/forms/charge-element/quantities.js, src/internal/modules/charge-information/forms/charge-element/season.js, src/internal/modules/charge-information/forms/charge-element/source.js, src/internal/modules/charge-information/forms/charge-element/time-limit.js, test/internal/modules/charge-information/forms/charge-elements/loss-category.js, test/internal/modules/charge-information/forms/charge-elements/purpose.js, test/internal/modules/charge-information/forms/charge-elements/quantities.js, test/internal/modules/charge-information/forms/charge-elements/season.js, test/internal/modules/charge-information/forms/charge-elements/time-limit.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3300
Goes along with: https://github.com/DEFRA/water-abstraction-service/pull/1496
=> WATER-3300

src/internal/modules/billing-accounts/pre-handlers.js, test/internal/modules/billing-accounts/pre-handlers.js
feat/water-3245
-- isRebillableBill prehandler fixed to match new logic in the service
=> Water - 3245 - is re-billable pre-handler fixed to follow new logic

src/internal/modules/billing-accounts/controllers/billing-accounts.js, src/internal/modules/billing-accounts/routes/billing-accounts.js, src/internal/views/nunjucks/billing-accounts/view.njk, test/internal/modules/billing-accounts/controllers/billing-accounts.js
Bugfix/water 3245 rebilling
-- Billing account page UI changed to hide re-issue bill button when no re-billable bills available.
=> bugfix/water-3245 - Billing Account page update

src/internal/modules/billing-accounts/controllers/billing-accounts.js, src/internal/modules/billing-accounts/routes/billing-accounts.js, src/internal/views/nunjucks/billing-accounts/view.njk, test/internal/modules/billing-accounts/controllers/billing-accounts.js
duplicate PR of https://github.com/DEFRA/water-abstraction-ui/pull/1912 for the release
=> duplicate PR for release - Bugfix/water 3245 rebilling

cypress/integration/internal/taging-untagging-icence-gauging-station.spec.js
This Automation story covers the below scenarios - 
Tagging a licence 
Untagging a licence 
Validation check for the empty form submissions
Automation story - Water-3244
=> Regression test/water 3244

src/internal/config.js, src/internal/views/nunjucks/billing/macros/batch-buttons.njk, src/internal/views/nunjucks/gauging-stations/gauging-station.njk
- Enables tagging for QAA
- Hides sending WAA button
- Hides 'Remove licence' from bill run button
=> Toggle flags

src/internal/views/nunjucks/gauging-stations/gauging-station.njk
Relates to https://eaflood.atlassian.net/browse/WATER-3310
=> Fix table accessibility issue as requested by UCD

cypress/integration/internal/annual-bills-run.spec.js, cypress/integration/internal/bills-tab.spec.js, cypress/integration/internal/charge-version-flow.spec.js, cypress/integration/internal/create-view-edit-delete-licence-agreements.spec.js, cypress/integration/internal/mark-licence-for-supplementary-billing.js, cypress/integration/internal/reset-password.spec.js, cypress/integration/internal/returns-status-view.spec.js, cypress/integration/internal/search-for-licence.spec.js, cypress/integration/internal/supplementary-bills-run.spec.js, cypress/integration/internal/taging-untagging-icence-gauging-station.spec.js, cypress/integration/internal/two-part-tariff-bill-run.spec.js, cypress/integration/internal/update-view-returns-status-of-a-licence.spec.js, src/internal/lib/view/main-nav.js, src/internal/modules/internal-search/routes.js, src/internal/views/nunjucks/internal-search/index.njk, src/shared/assets/sass/blocks/_search.scss
Changes as described in https://eaflood.atlassian.net/browse/WATER-3291
=> WATER-3291: Update Licences tab in Internal Service

cypress/integration/internal/annual-bills-run.spec.js, src/internal/lib/view/main-nav.js, src/internal/modules/billing/routes/bill-run.js, src/internal/modules/billing/routes/create-bill-run.js, src/internal/modules/manage/lib/manage-nav.js, src/internal/views/nunjucks/billing/batch-list.njk, test/internal/lib/view/main-nav.js, test/internal/modules/manage/controller.js
See https://eaflood.atlassian.net/browse/WATER-3290 for details
=> WATER-3290: Create a Bill runs tab

src/shared/lib/pre-handlers/licences.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3368
Service PR: https://github.com/DEFRA/water-abstraction-service/pull/1549
UI PR: https://github.com/DEFRA/water-abstraction-ui/pull/1965
CRM PR: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/871
=> Make expired licences searchable again

src/internal/modules/billing-accounts/lib/mapper.js, src/internal/modules/contact-entry/controller.js, src/internal/modules/contact-entry/forms/create-contact.js, src/internal/modules/customers/controllers.js, src/internal/modules/customers/forms/contactDepartment.js, src/internal/modules/customers/forms/contactName.js, src/internal/modules/customers/forms/index.js, src/internal/modules/customers/helpers.js, src/internal/modules/customers/routes.js, src/internal/views/nunjucks/customers/contact.njk, src/internal/views/nunjucks/customers/tabs/contacts.njk, src/shared/lib/mappers/contact.js, test/internal/modules/contact-entry/controller.js, test/internal/modules/contact-entry/forms/create-contact.js, test/internal/modules/customers/controllers.js, test/internal/modules/customers/forms/contactDepartment.js, test/internal/modules/customers/forms/contactName.js
See: https://eaflood.atlassian.net/browse/WATER-3193
Please note that this is dependant on the following PRs:
https://github.com/DEFRA/water-abstraction-service/pull/1552
https://github.com/DEFRA/water-abstraction-tactical-crm/pull/872
=> WATER-3193: Edit a contact and department separately

src/internal/modules/contact-entry/forms/select-contact.js, src/internal/modules/customers/controllers.js, src/internal/modules/customers/helpers.js, src/internal/views/nunjucks/customers/tabs/contacts.njk, test/internal/modules/customers/controllers.js
See: https://eaflood.atlassian.net/browse/WATER-3372
This is dependant upon PR: https://github.com/DEFRA/water-abstraction-service/pull/1553
=> WATER-3372: Generate the fullName for a companyContact in the service

src/internal/modules/customers/controllers.js, src/internal/modules/customers/forms/contact-removal/check-contact-for-removal.js, src/internal/modules/customers/forms/contact-removal/select-contact-for-removal.js, src/internal/modules/customers/forms/index.js, src/internal/modules/customers/routes.js, src/internal/views/nunjucks/customers/contact-removed.njk, src/internal/views/nunjucks/customers/tabs/contacts.njk, src/shared/lib/connectors/services/water/CompaniesService.js, src/shared/lib/constants.js, src/shared/lib/forms/fields/index.js, src/shared/lib/forms/fields/warningText.js, src/shared/view/nunjucks/macros/forms/warning-text.njk, src/shared/view/nunjucks/macros/forms/widget.njk, test/internal/modules/customers/controllers.js, test/internal/modules/customers/forms/contact-removal/check-contact-for-removal.js, test/internal/modules/customers/forms/contact-removal/select-contact-for-removal.js, test/lib/form-test.js, test/shared/lib/connectors/services/water/CompaniesService.js
See: https://eaflood.atlassian.net/browse/WATER-3349
Please note this PR is dependant upon PRs:
- https://github.com/DEFRA/water-abstraction-service/pull/1564
- https://github.com/DEFRA/water-abstraction-tactical-crm/pull/873
=> WATER-3349: Delete a company contact

cypress/integration/internal/remove-individual-licence-from-bill.js
See: https://eaflood.atlassian.net/browse/WATER-3215
This PR is a requirement for PR: https://github.com/DEFRA/water-abstraction-service/pull/1568
=> WATER-3215: Regression test for removing a licence from an invoice

src/shared/lib/forms/index.js, test/internal/modules/customers/controllers.js
See: https://eaflood.atlassian.net/browse/WATER-3379
Please note this PR depends on the following PRs:
https://github.com/DEFRA/water-abstraction-service/pull/1570
https://github.com/DEFRA/water-abstraction-tactical-crm/pull/875
=> WATER-3379: Update a contact, add a new charge version it throws error

src/internal/modules/customers/controllers.js, src/internal/views/nunjucks/customers/tabs/billing-accounts.njk
See: https://eaflood.atlassian.net/browse/WATER-3365
=> WATER-3365: Link only when can manage billing accounts

src/shared/plugins/reset-password/routes.js, test/shared/plugins/reset-password/routes.js
See: https://eaflood.atlassian.net/browse/WATER-3381
=> WATER 338: Allow forced query param on password reset url

cypress/integration/internal/recalculate-charges.spec.js, cypress/support/common.js
See: https://eaflood.atlassian.net/browse/WATER-3390
Please note this is dependant on PR: https://github.com/DEFRA/water-abstraction-service/pull/1592
=> WATER 3390: Recalculating charges with no change to charge versions for the historic Data

src/external/views/nunjucks/content/cookies.njk, src/internal/views/nunjucks/content/cookies.njk
See: https://eaflood.atlassian.net/browse/WATER-3394
=> WATER-3394: Update cookies expiry description

package.json
Adding Cypress commands for FF and Edge
=> Adding commands for edge and firefox

cypress/integration/internal/non-chargeable-licence-credits-back-historic-charges.spec.js, cypress/integration/internal/recalculate-charges.spec.js, cypress/support/common.js
See https://eaflood.atlassian.net/browse/WATER-3390 for the differing regression test scenarios.
Please note that this PR id dependant upon: https://github.com/DEFRA/water-abstraction-service/pull/1595
=> WATER-3390: Recalculate charges with changes

.eslintignore, cypress/integration/external/notify-callback.spec.js, cypress/integration/internal/billing-cancel-bill-run.spec.js, cypress/integration/internal/mark-licence-for-supplementary-billing.js, cypress/integration/internal/non-chargeable-licence-credits-back-historic-charges.spec.js, cypress/integration/internal/recalculate-charges.spec.js, cypress/integration/internal/remove-individual-licence-from-bill.spec.js, cypress/support/common.js, cypress/support/notifications.js
This PR will check Linting for Cypress tests
=> Linting added for Cypress Tests

src/internal/modules/notifications-reports/controller.js
Goes with https://github.com/DEFRA/water-abstraction-service/pull/1597
=> Enhancement to the lookup facility for notifications

src/external/views/nunjucks/content/cookies.njk, src/internal/views/nunjucks/content/cookies.njk
See: https://eaflood.atlassian.net/browse/WATER-3395?focusedCommentId=367856
=> WATER-3395: Add performance survey cookies section

src/internal/modules/charge-information/controllers/view-charge-information.js, test/internal/modules/charge-information/controllers/view-charge-information.js
feat/water-3429
-- isSrocChargeInfoEnabled added to view charge info controller
=>  Review sroc charge info WATER - 3429

src/internal/modules/charge-information/controllers/charge-category.js, src/internal/modules/charge-information/pre-handlers.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, test/internal/modules/charge-information/controllers/charge-category.js, test/internal/modules/charge-information/pre-handlers.js
See: https://eaflood.atlassian.net/browse/WATER-3409
=> WATER-3409: Add change links on Charge information review page

src/internal/modules/charge-information/lib/actions.js, src/internal/views/nunjucks/charge-information/view.njk
hotfix/water-3483
-- allow confirm button for charge info when start
date is after SROC go live date for ALCS scheme until Sroc is live
=> Hot fix for water 3483

src/internal/modules/charge-information/lib/actions.js, src/internal/views/nunjucks/charge-information/view.njk
Reverts DEFRA/water-abstraction-ui#2021
=> Revert "duplicate PR for release hotfix/water-3483"

src/internal/modules/charge-information/lib/actions.js, src/internal/views/nunjucks/charge-information/view.njk
Reverts DEFRA/water-abstraction-ui#2019
=> Revert "Hot fix for water 3483"

src/internal/modules/charge-information/forms/charge-category/default-radio-options-form.js, src/internal/modules/charge-information/forms/charge-category/volume.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, test/internal/modules/charge-information/forms/charge-categories/volume.js
This fixes the bugs mentioned here: https://eaflood.atlassian.net/browse/WATER-3409?focusedCommentId=373915
Please note that we are storing a maximum of 6 decimal places.
=> WATER-3409: Fix bugs

package-lock.json, src/internal/lib/connectors/services/water/SupportedSourcesService.js, src/internal/lib/connectors/services/water/index.js, src/internal/modules/charge-information/controllers/charge-category.js, src/internal/modules/charge-information/forms/charge-category/default-radio-options-form.js, src/internal/modules/charge-information/forms/charge-category/index.js, src/internal/modules/charge-information/forms/charge-category/supported-source-name-form.js, src/internal/modules/charge-information/lib/charge-categories/constants.js, src/internal/modules/charge-information/lib/helpers.js, src/internal/modules/charge-information/pre-handlers.js, src/internal/modules/charge-information/routes/charge-category.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, src/shared/assets/sass/application.scss, src/shared/assets/sass/blocks/_radios.scss, src/shared/view/nunjucks/filters/form.js, test/internal/lib/connectors/services/water/SupportedSourcesService.js, test/internal/modules/charge-information/controllers/charge-category.js, test/internal/modules/charge-information/pre-handlers.js, test/internal/modules/charge-information/routes/charge-categories.js
See:
- https://eaflood.atlassian.net/browse/WATER-3407
- https://eaflood.atlassian.net/browse/WATER-3409
- https://eaflood.atlassian.net/browse/WATER-3410
Please note that this also depends on: https://github.com/DEFRA/water-abstraction-service/pull/1614
=> WATER-3407: Create SRoC Charge Information

src/internal/modules/charge-information/controllers/charge-category.js, test/internal/modules/charge-information/controllers/charge-category.js
See: https://eaflood.atlassian.net/browse/WATER-3410
=> WATER-3410: Return to review page after supported source name update

src/internal/modules/charge-information/controllers/charge-category.js, src/internal/modules/charge-information/routes/charge-category.js, test/internal/modules/charge-information/controllers/charge-category.js
When making changes, the supply public water page is only included in the flow when the additional charges flag is changed from no to yes.
=> WATER-3410: Fix additional charges flow

src/internal/modules/charge-information/forms/start-date.js, src/internal/modules/charge-information/lib/actions.js, test/internal/modules/charge-information/controllers/charge-information.js, test/internal/modules/charge-information/controllers/non-chargeable.js, test/internal/modules/charge-information/forms/start-date.js, test/internal/modules/charge-information/lib/actions.js
https://eaflood.atlassian.net/browse/WATER-3393
=> Further modifications following discussion with PO and UCD

src/external/modules/content/routes.js, src/external/views/nunjucks/content/privacy-policy.njk, src/internal/modules/content/routes.js, src/internal/views/nunjucks/content/privacy-policy.njk
See: https://eaflood.atlassian.net/browse/WATER-3318?focusedCommentId=375777
=> WATER-3318: Update our Privacy Notice

src/internal/lib/view-engine/filters/alcs-exist.js, src/internal/lib/view-engine/filters/charge-purposes-descriptions.js, src/internal/lib/view-engine/filters/index.js, src/internal/modules/charge-information/controllers/charge-category.js, src/internal/modules/charge-information/controllers/charge-information.js, src/internal/modules/charge-information/forms/charge-category/adjustments.js, src/internal/modules/charge-information/forms/charge-category/default-radio-options-form.js, src/internal/modules/charge-information/forms/charge-category/description.js, src/internal/modules/charge-information/forms/charge-category/index.js, src/internal/modules/charge-information/forms/charge-category/supported-source-name-form.js, src/internal/modules/charge-information/forms/charge-category/volume.js, src/internal/modules/charge-information/forms/charge-category/which-element.js, src/internal/modules/charge-information/lib/actions.js, src/internal/modules/charge-information/lib/charge-categories/constants.js, src/internal/modules/charge-information/lib/helpers.js, src/internal/modules/charge-information/lib/reducer.js, src/internal/modules/charge-information/pre-handlers.js, src/internal/modules/charge-information/routes/charge-category.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-alcs.njk, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, test/internal/lib/view-engine/filters/alcs-exist.js, test/internal/lib/view-engine/filters/charge-purposes-description.js, test/internal/modules/charge-information/controllers/charge-category.js, test/internal/modules/charge-information/routes/charge-categories.js
See: https://eaflood.atlassian.net/browse/WATER-3458
=> WATER-3458: Select multiple charge elements screen

src/internal/views/nunjucks/charge-information/macros/charge-element-table-alcs.njk, src/internal/views/nunjucks/charge-information/view.njk
See: https://eaflood.atlassian.net/browse/WATER-3543
Also fixes: https://eaflood.atlassian.net/browse/WATER-3458?focusedCommentId=380292
=> WATER-3543: Prevent approve/update and submit with orphan charge element

src/internal/modules/charge-information/controllers/charge-information-workflow-note.js, src/internal/modules/charge-information/lib/routing.js, src/internal/modules/charge-information/pre-handlers.js, src/internal/modules/charge-information/routes.js, src/internal/modules/charge-information/routes/charge-information-workflow-note.js, src/internal/modules/notes/controller.js, src/internal/modules/notes/forms/index.js, src/internal/modules/notes/forms/note.js, src/internal/modules/notes/lib/session.js, src/internal/modules/notes/routes.js, src/internal/modules/routes.js, src/internal/views/nunjucks/charge-information/view.njk, src/shared/view/nunjucks/filters/form.js, src/shared/view/nunjucks/macros/forms/text.njk, test/internal/modules/charge-information/controllers/charge-information-workflow-note.js, test/internal/modules/charge-information/pre-handlers.js, test/internal/modules/notes/controller.js, test/shared/view/nunjucks/filters/form.js
See: https://eaflood.atlassian.net/browse/WATER-3415
This is dependant upon for: https://github.com/DEFRA/water-abstraction-service/pull/1636
=> WATER-3415: Addition of Notes to Charge Information review page

src/internal/modules/charge-information/controllers/charge-information-workflow-note.js, src/internal/modules/notes/controller.js, test/internal/modules/charge-information/controllers/charge-information-workflow-note.js
See: https://eaflood.atlassian.net/browse/WATER-3415
Fixes missed back link in the notes page.
=> WATER-3415: Addition of Notes - add back link

src/internal/modules/charge-information/controllers/charge-element.js, src/internal/modules/charge-information/forms/charge-category/default-radio-options-form.js, src/internal/modules/charge-information/forms/charge-element/quantities.js, src/internal/modules/charge-information/lib/charge-elements/constants.js, src/internal/modules/charge-information/lib/charge-information-validator.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-alcs.njk, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, test/internal/modules/charge-information/controllers/charge-element.js, test/internal/modules/charge-information/controllers/view-charge-information.js, test/internal/modules/charge-information/forms/charge-elements/quantities.js, test/internal/modules/charge-information/lib/charge-information-validator.js
Relates to https://eaflood.atlassian.net/browse/WATER-3485
Goes with https://github.com/DEFRA/water-abstraction-service/pull/1638
=> Adds handling for validation when CVW is SROC

src/external/lib/view-engine/filters/index.js, src/internal/lib/view-engine/filters/index.js, src/internal/views/nunjucks/internal-search/index.njk, src/internal/views/nunjucks/view-licences/macros/licence-summary.njk, src/internal/views/nunjucks/view-licences/macros/region.njk, src/shared/view/nunjucks/filters/year.js, test/shared/view/nunjucks/filters/year.js
This PR originated from this ticket: https://eaflood.atlassian.net/browse/WATER-3582
=> A new way of displaying licence expiry

src/internal/modules/charge-information/forms/charge-category/supported-source-name-form.js, src/internal/modules/charge-information/forms/charge-element/agreements.js, src/internal/modules/charge-information/lib/charge-categories/constants.js, src/internal/modules/charge-information/lib/charge-elements/constants.js, src/internal/views/nunjucks/charge-information/macros/charge-element-table-alcs.njk, src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk, src/shared/assets/sass/blocks/_radios.scss, test/internal/modules/charge-information/forms/charge-elements/agreements.js
Relates to https://eaflood.atlassian.net/browse/WATER-3523
=> A series of content changes as requested in WATER-3523

src/internal/config.js
See: https://eaflood.atlassian.net/browse/WATER-3495
Forces test for env variable ALLOW_CHARGE_VERSION_UPLOADS to check for "true"
=> WATER-3495: Feature flag must be true

src/internal/modules/billing/services/transactions-csv.js, test/internal/modules/billing/services/transactions-csv.js
-- fix minimum charge transactions
=> duplicate PR for bugfix/water-3613 for the release

cypress/integration/internal/sroc-charge-version-flow.spec.js, cypress/support/validation.js, src/internal/modules/charge-information/forms/charge-category/volume.js
https://eaflood.atlassian.net/browse/WATER-3632
We update the charge category volume validation to allow values of `0` and above.
=> Bugfix/water-3632 - allow charge category volume under 1ml

src/internal/modules/charge-information-upload/controller.js, src/internal/modules/charge-information-upload/form.js, src/internal/modules/charge-information-upload/routes.js, src/internal/modules/charge-information/routes.js, src/internal/modules/routes.js, src/internal/views/nunjucks/waiting/index.njk, src/shared/lib/upload-helpers.js, test/internal/modules/charge-information-upload/controller.js
See https://eaflood.atlassian.net/browse/WATER-3551
This also depends on: https://github.com/DEFRA/water-abstraction-service/pull/1655
=> WATER-3551: - Display status of upload

nodemon.json, package-lock.json, package.json
Addresses: https://github.com/DEFRA/water-abstraction-team/issues/11
=> chore: remove nodemon

README.MD
Addresses: https://github.com/DEFRA/water-abstraction-team/issues/18
=> chore: remove unused commands from readme

cypress/integration/internal/sroc-charge-version-adjustments-no.spec.js, cypress/integration/internal/sroc-charge-version-adjustments-option-yes.spec.js
https://eaflood.atlassian.net/browse/WATER-3567
Automation tests added for the Adjustment Option Yes and No.
=> SRoC Adjustments for Yes and No Options

cypress/integration/internal/billing-cancel-bill-run.spec.js, cypress/integration/internal/billing-two-part-tariff-bill-run.spec.js, cypress/integration/internal/sroc-select-multiple-charge-version.spec.js
https://eaflood.atlassian.net/browse/WATER-3679
=> Regression test/fixes

cypress/integration/internal/billing-annual-bills-run.spec.js
https://eaflood.atlassian.net/browse/WATER-3586
=> Download bill test is added

src/internal/modules/charge-information/forms/charge-category/volume.js
https://eaflood.atlassian.net/browse/WATER-3696
Updated error message as it was missed off the ticket originally
=> Handle 0 Volumes

cypress/integration/internal/billing/billing-annual-bills-run.spec.js, cypress/integration/internal/billing/billing-cancel-bill-run.spec.js, cypress/integration/internal/billing/billing-non-chargeable-licence-credits-back-historic-charges.spec.js, cypress/integration/internal/billing/billing-rebilling-supplementary.spec.js, cypress/integration/internal/billing/billing-supplementary-2part-historic-recalculate-charges.spec.js, cypress/integration/internal/billing/billing-two-part-tariff-bill-run.spec.js, cypress/integration/internal/billing/bills-tab.spec.js, cypress/integration/internal/billing/license-transfer-to-new-billing-account.spec.js, cypress/integration/internal/billing/mark-licence-for-supplementary-billing.spec.js, cypress/integration/internal/billing/remove-individual-licence-from-bill.spec.js, cypress/integration/internal/chargeinformation/change-user-permissions.spec.js, cypress/integration/internal/chargeinformation/create-view-edit-delete-licence-agreements.spec.js, cypress/integration/internal/chargeinformation/remove-charge-info-workflow.spec.js, cypress/integration/internal/chargeinformation/sroc-charge-version-adjustments-option-no.spec.js, cypress/integration/internal/chargeinformation/sroc-charge-version-adjustments-option-yes.spec.js, cypress/integration/internal/chargeinformation/sroc-charge-version.spec.js, cypress/integration/internal/chargeinformation/sroc-edit-submit-review-view-charge-version.spec.js, cypress/integration/internal/chargeinformation/sroc-select-multiple-charge-version.spec.js, cypress/integration/internal/returns/invite-licence-holders-submit-returns.spec.js, cypress/integration/internal/returns/remind-licence-holders-submit-returns.spec.js, cypress/integration/internal/returns/returns-status-view.spec.js, cypress/integration/internal/returns/update-view-returns-status-of-a-licence.spec.js, cypress/integration/internal/user/create-user.spec.js, cypress/integration/internal/user/reset-password.spec.js, cypress/integration/internal/user/search-for-licence.spec.js, cypress/integration/internal/user/view-contacts.spec.js, cypress/integration/internal/waa/gauging-stations-and-water-abstraction-alerts-mbod.spec.js, cypress/integration/internal/waa/gauging-stations-and-water-abstraction-alerts.spec.js, cypress/integration/internal/waa/paper-forms-flow.ci.spec.js
https://eaflood.atlassian.net/browse/WATER-3748
=> Tests grouped and updated

cypress/integration/internal/chargeinformation/sroc-select-multiple-charge-version.spec.js, cypress/support/sroc-charge-version.js
Fixing annual billing and select multiple charge version
=> Test fixes

.env.example, src/internal/config.js, src/internal/lib/connectors/services/water/SystemProxyService.js, src/internal/modules/routes.js, src/internal/modules/system-proxy/controller.js, src/internal/modules/system-proxy/routes.js, test/internal/modules/system-proxy/controller.test.js, test/internal/modules/system-proxy/routes.test.js
https://eaflood.atlassian.net/browse/WATER-3787
We create a proxy endpoint so that we can check that the system is working.
=> Create system proxy endpoint

src/internal/modules/manage/lib/manage-nav.js, test/internal/modules/manage/lib/manage-nav.test.js
https://eaflood.atlassian.net/browse/WATER-4782
This PR is adding a new link on the manage page.
=> Ad hoc returns link on manage page
